half of the slim files to html
cesium/atomic pull request #247
Opened 2022-07-07 14:27 UTC by jotaalvim

2022-07-07 14:32 UTC, miguelbrandao requested changes

2022-07-07 14:32 UTC, miguelbrandao commented on app/views/activities/_activities_breadcrumb.html.erb
> +-- >
Remove this

2022-07-07 14:32 UTC, miguelbrandao commented on app/views/activities/_form.html.erb
> +; _slim_controls2 << ("<br".freeze); _slim_controls2 << (" />".freeze);
remove the slim controlls

2022-07-20 18:01 UTC, nelsonmestevao commented on app/views/activities/_activities_breadcrumb.html.erb
> +
```suggestion
```

2022-07-20 18:02 UTC, nelsonmestevao commented on app/views/activities/_form.html.erb
> +        class: "btn btn-lg btn-delete border-theme" %>
```suggestion
        class: "btn btn-lg btn-delete border-theme" %>
     <% end %>
```

2022-12-01 21:14 UTC, ruioliveira02 commented
We are refactoring this in Elixir, so this PR is no longer useful. Thank you for contributing pray

2022-12-01 21:14 UTC, closed without merging