Update activities departments relation to a many to many
cesium/atomic pull request #260
Opened 2022-12-09 20:14 UTC by feliciofilipe

2022-12-09 22:33 UTC, MarioRodrigues10 commented
It is not possible to update or remove departments and speakers from activities.

2022-12-09 22:33 UTC, MarioRodrigues10 requested changes
It is not possible to update or remove departments and speakers from activities.

2023-02-19 00:44 UTC, feliciofilipe commented
@MarioRodrigues10 review it again plz :pray:

2023-02-19 16:16 UTC, MarioRodrigues10 requested changes
In order to fix this error when creating a new activity ```unknown field `:department_id` given to cast.```.

2023-02-19 16:16 UTC, MarioRodrigues10 commented on lib/atomic/activities/activity.ex
>    @required_fields ~w(title description
Please remove department_id from @required_fields

2023-02-19 17:35 UTC, MarioRodrigues10 commented on lib/atomic/activities/activity.ex
> -    belongs_to :department, Department
Due to this change ``` field `department_id` in `where` does not exist in schema Atomic.Activities.Activity ```, so it isn't possible to edit or create a department

2023-02-19 18:53 UTC, MarioRodrigues10 commented on lib/atomic/activities/activity.ex
> -    belongs_to :department, Department
This wasn't resolved

2023-02-19 18:53 UTC, MarioRodrigues10 requested changes

2023-02-19 18:53 UTC, MarioRodrigues10 commented on lib/atomic/activities/activity.ex
> -    belongs_to :department, Department
This wasn't resolved

2023-02-19 18:58 UTC, MarioRodrigues10 approved these changes
Approved because the department form issue is solved in #266

2023-02-19 19:00 UTC, merged