Add collaborators
cesium/atomic pull request #264
Opened 2023-01-14 14:51 UTC by MarioRodrigues10

2023-01-25 17:20 UTC, ruioliveira02 requested changes

2023-01-25 17:20 UTC, ruioliveira02 commented on lib/atomic/accounts/user.ex
> +    has_one :collaborator, Collaborator, on_replace: :delete_if_exists, on_delete: :delete_all
```suggestion
    has_many :collaborator, Collaborator, on_replace: :delete_if_exists, on_delete: :delete_all
```
A user can be a collaborator of multiple departments

2023-01-25 17:20 UTC, ruioliveira02 commented on test/support/fixtures/accounts_fixtures.ex
> +  end
We should use factories for testing (not saying to do it here, just mentioning in general)

2023-01-29 15:48 UTC, feliciofilipe commented on lib/atomic/accounts/collaborator_department.ex
> +  schema "collaborator_departments" do
Should we not have a role to identify this relation, e.g.: 'President', 'Vice-President', etc?

2023-01-29 15:49 UTC, feliciofilipe commented on lib/atomic/accounts/user.ex
> +    has_one :collaborator, Collaborator, on_replace: :delete_if_exists, on_delete: :delete_all
collaborators*

2023-01-29 22:14 UTC, MarioRodrigues10 commented on lib/atomic/accounts/collaborator_department.ex
> +  schema "collaborator_departments" do
I thought about creating another schema "board_users" where i give those roles to an user

2023-02-19 01:58 UTC, feliciofilipe commented
We need to discuss this carefully before going foward

2023-03-07 12:26 UTC, MarioRodrigues10 commented on lib/atomic/accounts/user.ex
> +    has_one :collaborator, Collaborator, on_replace: :delete_if_exists, on_delete: :delete_all
I updated to a many_to_many relationship

2023-03-07 12:28 UTC, MarioRodrigues10 commented on lib/atomic/accounts/collaborator_department.ex
> +  schema "collaborator_departments" do
Inside this schema i can create ```  role field ``` and give it to user , what you think?

2023-07-03 22:05 UTC, RuiL1904 commented on lib/atomic/accounts/collaborator_department.ex
> +    An activity speaker
```suggestion
    A relation representing a collaborator who belongs to a department
```

2023-07-19 10:05 UTC, ruioliveira02 reviewed
As collaborators change every year you should add the year as a field IMO

2023-07-19 10:05 UTC, ruioliveira02 commented on priv/repo/migrations/20230114142351_create_collaborator_departments.exs
> +      add :collaborator_id, references(:users, on_delete: :nothing, type: :binary_id)
```suggestion
      add :user_id, references(:users, on_delete: :nothing, type: :binary_id)
```

2023-07-19 10:05 UTC, ruioliveira02 commented on lib/atomic/accounts/collaborator_department.ex
> +    belongs_to :collaborator, User
```suggestion
    belongs_to :user, User
```

2023-08-10 21:22 UTC, closed without merging

2023-08-10 21:22 UTC, MarioRodrigues10 commented
This was closed because it was done in #291