Add associations
cesium/atomic pull request #273
Opened 2023-03-17 12:48 UTC by ruioliveira02

An association is when a user ask to be a part of an organization. That request can be approved or dismissed by an admin of the org.

2023-03-17 16:24 UTC, MarioRodrigues10 requested changes

2023-03-17 16:24 UTC, MarioRodrigues10 commented on lib/atomic_web/live/association_live/form_component.ex
> +      if not number do
```suggestion
      if is_nil(number) do
```

2023-03-17 16:24 UTC, MarioRodrigues10 commented on lib/atomic_web/live/association_live/index.html.heex
> +  <table :class="[toggle ? 'hidden' : 'block']">
It should be possible to always edit an association.

2023-03-18 08:37 UTC, MarioRodrigues10 requested changes

2023-03-18 08:37 UTC, MarioRodrigues10 commented on lib/atomic/organizations.ex
> +  alias Jason.Encoder.Ecto.Association
Remove this line pleas

2023-03-18 08:37 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/show.ex
> +  def handle_event("sign_up", _params, socket) do
```suggestion
  def handle_event("sign_up", _payload, socket) do
```

2023-03-18 18:17 UTC, MarioRodrigues10 approved these changes
:heart: :orange_heart:

2023-03-18 18:41 UTC, feliciofilipe requested changes
The best term for this use case is `Member`

2023-03-18 18:41 UTC, feliciofilipe commented on lib/atomic/accounts/user.ex
> +    many_to_many :organizations, Organization, join_through: Association
```suggestion
    many_to_many :organizations, Organization, join_through: Member
```

2023-03-18 18:41 UTC, feliciofilipe commented on lib/atomic/accounts/user.ex
> +  alias Atomic.Organizations.{Association, Organization}
```suggestion
  alias Atomic.Organizations.{Member, Organization}
```

2023-03-22 17:24 UTC, MarioRodrigues10 requested changes

2023-03-23 14:25 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/show.html.heex
> +<button phx-click="follow">Follow</button>
It returns an error, when pressed twice

2023-03-23 14:26 UTC, MarioRodrigues10 commented on lib/atomic_web/router.ex
> +      live "/memberships/:org/new", MembershipLive.New, :new
User should show email or name and not id

2023-03-23 19:51 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/show.html.heex
> +<button phx-click="follow">Follow</button>
Actually this button should disappear if they already follow or if there's a pending invite

2023-03-23 20:34 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/show.html.heex
> +<button phx-click="follow">Follow</button>
Actually this button should disappear if they already follow or if there's a pending invite

2023-03-25 15:04 UTC, merged