Add extra user info
cesium/atomic pull request #277
Opened 2023-03-28 10:52 UTC by ruioliveira02

Add name, major and profile picture

2023-03-28 21:31 UTC, MarioRodrigues10 commented on lib/atomic/uploaders/profile_picture.ex
> +defmodule Atomic.Uploaders.ProfilePicture do
Although Plug.Upload provides a basic level of protection against large files, it's a good idea to implement additional safeguards to prevent users from attempting to upload files that are too large.
You can do this by adding client-side validation to your file upload form to check the size of the selected file before it's uploaded.

2023-03-28 21:32 UTC, MarioRodrigues10 commented on priv/uploads/atomic/profile_pictures/f42ae074-5d53-4da2-a38f-b9c8f2a36435/medium.png
Perfect image :+1:

2023-03-28 21:34 UTC, RuiL1904 commented on priv/uploads/atomic/profile_pictures/f42ae074-5d53-4da2-a38f-b9c8f2a36435/medium.png
It should be on `.gitignore` tho 😄

2023-03-28 21:34 UTC, MarioRodrigues10 commented on lib/atomic/uploaders/profile_picture.ex
Provide a default_url in case there's no image

2023-04-01 04:16 UTC, MarioRodrigues10 requested changes
Make sure to remove :owner and :number as a role in ``` lib/atomic/organizations/membership.ex ```

2023-04-03 09:45 UTC, ruioliveira02 commented
> Make sure to remove :owner and :number as a role in `lib/atomic/organizations/membership.ex`

This will be done in #278

2023-04-03 11:51 UTC, feliciofilipe commented on data/majors.txt
I would call this file: `coures.txt`. I think `marjos` is the terms for a master in a liberal arts type course.

2023-04-07 18:21 UTC, MarioRodrigues10 commented on lib/atomic/accounts/major.ex
Rename the file

2023-04-07 18:43 UTC, MarioRodrigues10 requested changes

2023-04-07 18:43 UTC, MarioRodrigues10 commented on lib/atomic/accounts/user.ex
> +  @required_fields ~w(email password role name course_id)a
Why is course_id a required_field?
I think it should be an optional field

2023-04-07 18:43 UTC, MarioRodrigues10 commented on priv/repo/seeds/accounts.exs
> +          Enum
```suggestion
```

2023-04-07 18:43 UTC, MarioRodrigues10 commented on priv/repo/seeds/accounts.exs
> +    courses = Atomic.Repo.all(Atomic.Accounts.Course)
Do some alias , instead of this

2023-04-08 13:29 UTC, MarioRodrigues10 approved these changes

2023-04-08 19:45 UTC, merged