Add boards
cesium/atomic pull request #278
Opened 2023-03-30 14:50 UTC by ruioliveira02

2023-04-01 04:00 UTC, MarioRodrigues10 requested changes
While you're doing this please make sure to the following things:
1 - At ``` lib/atomic/organizations/membership.ex ```  remove owner and number from roles.

2023-04-01 04:05 UTC, MarioRodrigues10 commented on lib/atomic_web/live/board_live/index.ex
> +    {:ok, uo} = Organizations.delete_user_organization(user_organization)
```suggestion
    {:ok, user_org} = Organizations.delete_user_organization(user_organization)
```

2023-04-01 04:05 UTC, MarioRodrigues10 commented on lib/atomic_web/live/board_live/index.ex
> +    {:noreply, assign(socket, :users_organizations, list_users_organizations(uo.organization_id))}
```suggestion
    {:noreply, assign(socket, :users_organizations, list_users_organizations(user_org.organization_id))}
```

2023-04-01 04:10 UTC, MarioRodrigues10 commented on test/support/fixtures/organizations_fixtures.ex
> +  Generate an user organization.
Shouldn't a membership with admin role also be generated?

2023-04-01 04:12 UTC, MarioRodrigues10 commented on lib/atomic/organizations.ex
> +  def list_users_organizations(opts \\ [], preloads \\ []) do
```suggestion
  def list_users_organizations(opts \\ [], preloads \\ []) do
```
Make sure to update documentation in order with the function

2023-04-01 04:12 UTC, MarioRodrigues10 commented on lib/atomic/organizations.ex
> +  def get_user_organization!(id, preloads \\ []) do
Make sure to update documentation in order with the function

2023-04-01 04:12 UTC, MarioRodrigues10 commented on lib/atomic/organizations.ex
> +  def change_user_organization(%UserOrganization{} = user_organization, attrs \\ %{}) do
Make sure to update documentation in order with the function

2023-04-03 09:44 UTC, ruioliveira02 commented on test/support/fixtures/organizations_fixtures.ex
> +  Generate an user organization.
Why?

2023-04-07 18:17 UTC, MarioRodrigues10 requested changes

2023-04-07 18:17 UTC, MarioRodrigues10 commented on lib/atomic/ecto/year.ex
> +  defp format(year) do
This should be something like this:

```c
def format(year) when not is_binary(year), do: {:error, :invalid_input}
def format(year) when not Regex.match?(~r/\A\d+\/\d+\z/, year), do: {:error, :invalid_format}

def format(year) do
  %{"first" => first_str, "second" => second_str} = Regex.named_captures(~r/\A(?<first>\d+)\/(?<second>\d+)\z/, year)
  
  {first, _} = Integer.parse(first_str)
  {second, _} = Integer.parse(second_str)
  
  case second - first do
    1 -> {:ok, year}
    _ -> {:error, :year_mismatch}
  end
end
```

2023-04-07 18:17 UTC, MarioRodrigues10 commented on lib/atomic/organizations.ex
>    def roles_less_than_or_equal(role) do
This function isn't handling all possible cases.
For example,  the example that you provided ```roles_less_than_or_equal(:member)``` it would fail.

2023-04-07 18:36 UTC, MarioRodrigues10 approved these changes
:rocket:

2023-04-07 18:38 UTC, merged