Add certificate generation for activities
cesium/atomic pull request #281
Opened 2023-04-14 14:56 UTC by ruioliveira02

Notes before merging:
- Tailwind is not working in email templates
- Seeds will need to be updated to add more variety to times in activities
- I still want to document the module
- There is no styling on emails and PDFs: this is on purpose and will be added in another PR

To test:
- Go to `config/config.exs` and change the `@daily` with `"* * * * *"`. This will make the task run every minute.

How does this work:
- This task will run at midnight every day (the choice of midnight - and this will be documented in the code - is because no activity would ever go beyond midnight: most would be from 9am:6pm)
- As a result, the task will search for all activities which ended (by ended we mean their last session ended) within the last 24 hours (as the task runs daily)

2023-04-20 22:09 UTC, MarioRodrigues10 commented on config/config.exs
> +    # Runs every midnight:
Which midgnight? Lisbon UTC?

2023-04-20 22:10 UTC, MarioRodrigues10 commented on lib/atomic_web/emails/activity_emails.ex
> +    |> reply_to("caos@cesium.di.uminho.pt")
```suggestion
    |> reply_to("support@atomic.cesium.pt")
```

2023-04-20 22:13 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/email/activity_certificate.html.eex
> +            o certificado de participação. Alternativamente, podes consultar o certificado no teu perfil da plataforma Atomic.
```suggestion
            <p>Gostávamos de agradecer a tua participação na atividade <%= @enrollment.activity.title %>. Enviamos, em anexo,
            o certificado de participação. Alternativamente, podes consultar o certificado no teu perfil.
```

We should not mention Atomic every time, we could have Atomic logo in the feature but there's no need to be mentioning it all the time.

2023-04-20 22:13 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/email/activity_certificate.html.eex
> +            <p>Este email foi gerado automaticamente. Por favor não respondas para este endereço de email.</p>
```suggestion
            <p>Este email foi gerado automaticamente. Por favor não respondas para este endereço de email, para alguma dúvida envia email para <%= organization.email %> .</p>
```

2023-04-20 22:16 UTC, MarioRodrigues10 requested changes
Please work on these small things

2023-04-22 21:09 UTC, ruioliveira02 commented on config/config.exs
> +    # Runs every midnight:
Whenever midnight is in the server's timezone. Meaning, it will most likely be in UTC

2023-04-22 21:10 UTC, ruioliveira02 commented on lib/atomic_web/templates/email/activity_certificate.html.eex
> +            <p>Este email foi gerado automaticamente. Por favor não respondas para este endereço de email.</p>
The problem is getting the organization will be a PITA. I was hoping to be able to trap someone else to do it

2023-04-22 21:16 UTC, ruioliveira02 commented on lib/atomic_web/templates/email/activity_certificate.html.eex
> +            <p>Este email foi gerado automaticamente. Por favor não respondas para este endereço de email.</p>
Plus I don't think that with the `reply_to` set it makes sense to include that text.

2023-04-22 21:25 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/email/activity_certificate.html.eex
> +            <p>Este email foi gerado automaticamente. Por favor não respondas para este endereço de email.</p>
Well , users report to organizations and organizations report to us if there is any problem. At least that's what i think that should happen.

2023-04-22 21:37 UTC, ruioliveira02 commented on lib/atomic_web/templates/email/activity_certificate.html.eex
> +            <p>Este email foi gerado automaticamente. Por favor não respondas para este endereço de email.</p>
Sure. I still don't think we should be too hung up on this, as this is not the version that will be in production and is just a placeholder

2023-04-26 13:17 UTC, MarioRodrigues10 requested changes

2023-04-26 13:17 UTC, MarioRodrigues10 commented on lib/atomic/quantum/certificate_delivery.ex
> +  end
```suggestion
  defp last_sessions_query() do
    now = DateTime.utc_now()
    minimum_finish = DateTime.add(now, -24, :hour)

    sq =
      from s in Session,
        where: s.finish >= ^minimum_finish and s.finish <= ^now,
        group_by: [s.activity_id],
        select: %{finish: max(s.finish), activity_id: s.activity_id}

    from s in subquery(sq),
      select: s.activity_id
  end
```

2023-04-26 13:17 UTC, MarioRodrigues10 commented on lib/atomic/quantum/certificate_delivery.ex
> +    for enrollment <- enrollments do
```suggestion
    included_enrollments()
    |> Enum.each(fn enrollment -> 
```

2023-04-26 16:35 UTC, MarioRodrigues10 requested changes

2023-04-26 16:35 UTC, MarioRodrigues10 commented on priv/repo/seeds/activities.exs
Please add a %Location{} for each ActivitySession

2023-04-29 21:32 UTC, MarioRodrigues10 approved these changes

2023-04-29 21:35 UTC, merged