Fix user fixtures
cesium/atomic pull request #285
Opened 2023-07-03 21:09 UTC by danielsp45

Some of the tests were failing duo to User fixtures being used in the tests, so I added ex-machina

2023-07-03 21:54 UTC, RuiL1904 commented on mix.exs
> +      {:quantum, "~> 3.0"},
Why is `quantum` needed?

2023-07-03 21:55 UTC, danielsp45 commented on mix.exs
> +      {:quantum, "~> 3.0"},
I'm not sure, it was already there

2023-07-03 21:55 UTC, RuiL1904 commented on mix.exs
> +      {:argon2_elixir, "~> 3.0"},
We should only use one of these algorithms. I think atomic is using bcrypt, but check it yourself.

2023-07-03 21:55 UTC, RuiL1904 commented on mix.exs
> +      # Uploads
```suggestion
      # uploads
```

2023-07-03 21:56 UTC, RuiL1904 commented on mix.exs
> +      {:esbuild, "~> 0.4", runtime: Mix.env() == :dev},
This should be moved to `# frontend` category.

2023-07-03 21:57 UTC, RuiL1904 commented on mix.exs
> +      {:floki, ">= 0.30.0", only: :test},
Why is this needed?

2023-07-03 22:00 UTC, RuiL1904 commented on mix.exs
> +      {:quantum, "~> 3.0"},
Quantum is intended for cron jobs. We are planning to implement it in bokken ([#155](https://github.com/coderdojobraga/bokken/pull/155)), for example.
You can remove it for now 🙏🏼

2023-07-03 22:42 UTC, RuiL1904 commented on mix.exs
> +      {:quantum, "~> 3.0"},
It is being used, my bad. Check this module: `Atomic.Quantum.CertificateDelivery`

2023-07-03 22:53 UTC, MarioRodrigues10 commented
I think instead of doing a PR fixing user fixtures, you could fix all tests since you're already change a few of them, what you think?

2023-07-04 16:32 UTC, RuiL1904 commented
@MarioRodrigues10 We should leave tests for new comers to make 👀

2023-07-10 22:41 UTC, MarioRodrigues10 commented on test/support/factories/accounts_factory.ex
> +          id: Faker.UUID.v4(),
```suggestion
```

2023-07-10 22:42 UTC, MarioRodrigues10 commented on test/atomic_web/controllers/user_auth_test.exs
> +      |> Phoenix.ConnTest.init_test_session(%{})
```suggestion
      |> init_test_session(%{})
```

2023-07-10 22:46 UTC, MarioRodrigues10 commented on test/atomic_web/controllers/page_controller_test.exs
> -  end
```c
  test "GET /", %{conn: conn} do
    conn = get(conn, "/")
    assert html_response(conn, 200) =~ "Listing Activities"
  end
```

2023-07-10 22:53 UTC, MarioRodrigues10 requested changes
Also there's some inconsistency because you erased some live tests and kept others.

2023-07-12 21:27 UTC, MarioRodrigues10 approved these changes

2023-07-12 21:27 UTC, MarioRodrigues10 commented
Great work :rocket:

2023-07-12 21:27 UTC, merged