Update sidebar and activity page
cesium/atomic pull request #289
Opened 2023-07-14 16:00 UTC by ferjpires

2023-07-14 17:08 UTC, MarioRodrigues10 requested changes

2023-07-14 17:08 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/layout/root.html.heex
> +        </div>
```suggestion
      <div class="flex">
```

2023-07-14 17:08 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/layout/root.html.heex
> +            </svg>
Align this to right side

Also instead of `<svg>` use HeroIcons, you can use it like:
```c
<Heroicons.Solid.pencil class="mr-3 w-5 h-5 text-gray-400" /> 
```

The documentation is here [https://hexdocs.pm/ex_heroicons/Heroicons.html](url)

2023-07-14 17:08 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/layout/root.html.heex
> +    </script>
This should be handle in assets , you don't need this amount of javascript you can use alpine to handle that

2023-07-14 17:08 UTC, MarioRodrigues10 commented on lib/atomic_web/live/activity_live/index.html.heex
> +  </script>
What is the purpose of this?

2023-07-14 17:08 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/layout/root.html.heex
This amount of `<svg />`  should be HeroIcons

2023-09-23 11:48 UTC, RuiL1904 commented
Already done.

2023-09-23 11:48 UTC, closed without merging