Add styling to activity certificates
cesium/atomic pull request #306
Opened 2023-08-11 21:15 UTC by ruioliveira02

2023-08-11 21:27 UTC, MarioRodrigues10 requested changes

2023-08-11 21:27 UTC, MarioRodrigues10 commented on lib/atomic_web/views/helpers.ex
> +  def display_enum(enum) do
Please make some doc tests for this function

2023-08-11 21:27 UTC, MarioRodrigues10 commented on lib/atomic/quantum/certificate_delivery.ex
> +      |> Enum.map(fn o -> Repo.get_by!(Organization, id: o).name end)
Departments are now associated to a session please remake this

2023-08-11 21:27 UTC, MarioRodrigues10 commented on lib/atomic/quantum/certificate_delivery.ex
> +      |> Repo.preload([:departments])
There's a function that already does this no need to rewrite code.

2023-08-17 14:14 UTC, MarioRodrigues10 submitted a review, later dismissed

2023-08-17 14:14 UTC, MarioRodrigues10 commented on lib/atomic_web/templates/pdf/activity_certificate.html.eex
> +            background: url('http://localhost:4000/images/atomic.png') no-repeat center;
```suggestion
            background: url('http://localhost:4000/images/atomic.png') no-repeat center;
```
This won't work in prod

2023-08-17 17:53 UTC, ruioliveira02 commented on lib/atomic_web/templates/pdf/activity_certificate.html.eex
> +            background: url('http://localhost:4000/images/atomic.png') no-repeat center;
It would because the rendering happens server side, and in the production server `localhost` is prod anyway. However I do agree it is not the best thing in the world, so I will change it when I have the time

2023-08-19 18:07 UTC, RuiL1904 commented on lib/atomic/quantum/certificate_delivery.ex
> +        )
In the future, we should think of a way to save this logs 💡

2023-08-19 18:10 UTC, RuiL1904 commented on lib/atomic_web/views/helpers.ex
> +  @doc ~S"""
```suggestion
  @doc """
```
> Elixir supports some sigil variants to deal with escaping characters and interpolation. In particular, uppercase letters sigils do not perform interpolation nor escaping. For example, although both ~s and ~S will return strings, the former allows escape codes and interpolation while the latter does not.

We don't need this there, then.

2023-08-24 19:45 UTC, RuiL1904 requested changes
Don't forget to change `@daily` to `0 0 * * *`, in order for the job to actually run at every midnight.

2023-09-23 19:06 UTC, RuiL1904 approved these changes

2023-09-25 11:00 UTC, merged