Update email confirmation
cesium/atomic pull request #307
Opened 2023-08-11 21:16 UTC by ruioliveira02

Now the pages are styled and there is a plug which restricts access to routes to users that have already been confirmed via email

2023-08-11 21:32 UTC, MarioRodrigues10 commented on lib/atomic_web/router.ex
>      get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
Is this route enough to confirm an account?
Shouldn't there be something like:
```
    get "/confirm", UserConfirmationController, :new
    post "/confirm", UserConfirmationController, :create
    get "/confirm/:token", UserConfirmationController, :edit
    post "/confirm/:token", UserConfirmationController, :update
```

2023-08-11 21:33 UTC, MarioRodrigues10 requested changes
Also please make sure CI passes

2023-08-11 22:18 UTC, MarioRodrigues10 requested changes
After i register this logs me in instead of redirecting to login page.

2023-08-12 13:38 UTC, ruioliveira02 commented on lib/atomic_web/router.ex
>      get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
No

2023-08-12 15:24 UTC, MarioRodrigues10 approved these changes
:rocket:

2023-08-12 15:24 UTC, merged