Fix & improve schemas, models and migrations
cesium/atomic pull request #318
Opened 2023-08-14 17:25 UTC by RuiL1904

2023-08-14 23:52 UTC, MarioRodrigues10 requested changes

2023-08-14 23:52 UTC, MarioRodrigues10 commented on lib/atomic/partnerships/partner.ex
> +  @optional_fields ~w(description)a
```suggestion
  @optional_fields ~w(description image)a
```

2023-08-18 22:42 UTC, MarioRodrigues10 requested changes
There will be some problems in activities seeds due to changes in field types , some make sure to merge #312  first and then solve those issues before i approve this.
The rest of the code is looking good, that's only thing stopping me from approving this.

2023-08-18 22:46 UTC, RuiL1904 commented on lib/atomic/activities/activity.ex
> +    |> cast_assoc(:activity_sessions, with: &Session.changeset/2)
```suggestion
    |> cast_assoc(:activity_sessions, required: true)
```

2023-08-22 21:05 UTC, danielsp45 approved these changes, later dismissed

2023-08-22 23:30 UTC, RuiL1904 commented
Needs other PRs to be merged first 🙃

2023-08-23 17:35 UTC, MarioRodrigues10 approved these changes
What a great work :rocket:

2023-08-23 17:36 UTC, merged