feat: add news related live views
cesium/atomic pull request #329
Opened 2023-08-19 16:38 UTC by RuiL1904

2023-08-19 16:42 UTC, RuiL1904 commented
/reviewpad summarize

2023-08-19 16:44 UTC, RuiL1904 commented
I think "News" is not a good name, for two main reasons:
1. The plural and singular are the same
2. It makes hard to read the code for the above reason

What do you guys (@cesium/atomic-23-24) think? Does anyone have a better name suggestion?

2023-08-19 21:38 UTC, danielsp45 requested changes

2023-08-19 21:38 UTC, danielsp45 commented on priv/repo/seeds/news.exs
Don't forget to change `%New{}` to `%News{}` in the for loop.
The seeds are failing.

2023-08-19 21:53 UTC, danielsp45 commented
<img width="1076" alt="image" src="https://github.com/cesium/atomic/assets/46000449/6d1281fb-3a1e-4ddd-b251-4e2006cf3072">
The Edit and Delete buttons are looking a bit inconsistent in terms of positioning

2023-08-20 12:34 UTC, RuiL1904 commented
@danielsp45 Can you check if the positioning is better now? 🙏🏼

2023-08-20 18:23 UTC, danielsp45 approved these changes
Great work🚀

2023-08-20 18:29 UTC, merged