feat: add activity forms
cesium/atomic pull request #354
Opened 2023-08-22 22:28 UTC by danielsp45

2023-09-18 22:14 UTC, RuiL1904 commented on assets/css/app.css
> +@import "tailwindcss/utilities";
`git checkout develop -- assets/css/app.css`

2023-09-18 22:14 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/form_component.ex
> +  @extensions_whitelist ~w(.jpg .jpeg .gif .png)
```suggestion
```

2023-09-18 22:14 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/form_component.ex
> +     |> allow_upload(:image, accept: @extensions_whitelist, max_entries: 1)}
```suggestion
     |> allow_upload(:image, accept: Atomic.Uploader.extensions_whitelist(), max_entries: 1)}
```

2023-09-18 22:14 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/form_component.html.heex
> +                Departments
Activities don't depend on departments anymore.

2023-09-18 22:14 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/index.ex
> +     |> assign(:current_user, socket.assigns.current_user)
Why is this assign needed? The `current_user` is injected in all live views, by a hook present at the router level.

2023-09-18 22:14 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/index.html.heex
> +        <.empty_state id="empty_state" url={Routes.activity_new_path(@socket, :new, @current_user.current_organization)} plural_placeholder="activities" placeholder="activity" />
`@current_organization` should be enough.

2023-09-18 22:14 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/new.ex
> +     |> assign(:current_organization, organization)
This assign is also not needed, by the reasons stated above.

2023-11-09 14:41 UTC, joaodiaslobo requested changes

2023-11-09 14:41 UTC, joaodiaslobo commented on lib/atomic_web/live/activity_live/form_component.html.heex
> +                </ul>
Can you make this a reusable component?

2023-11-09 14:41 UTC, joaodiaslobo commented on lib/atomic_web/live/activity_live/form_component.html.heex
> +                          "inset-y-0 right-0 flex-row pr-4 text-indigo-600"
```suggestion
                          "inset-y-0 right-0 flex-row pr-4 text-orange-500"
```

2023-11-09 14:41 UTC, joaodiaslobo commented on lib/atomic_web/components/forms.ex
> +        <%= textarea(@forms, @id, placeholder: @placeholder, rows: @rows, phx_debounce: "blur", class: "h-32 w-full rounded-md border-gray-300 font-medium shadow-sm focus:border-orange-500 focus:ring
```suggestion
        <%= textarea(@forms, @id, placeholder: @placeholder, rows: @rows, phx_debounce: "blur", class: "h-32 w-full rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500") %>
```

2023-11-10 12:39 UTC, diogogmatos commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Activity Forms](https://trello.com/c/HcjeBXa6/2-add-activity-forms)

2023-11-16 15:09 UTC, danielsp45 commented on lib/atomic_web/live/activity_live/form_component.html.heex
> +                          "inset-y-0 right-0 flex-row pr-4 text-indigo-600"
This is a small icon. I think indigo looks better than orange

2023-11-22 14:32 UTC, joaodiaslobo requested changes
Can you make it so that, when the multiselect component focus is lost, it closes?

<img width="296" alt="image" src="https://github.com/cesium/atomic/assets/30907944/0acd5e66-70f0-43f3-be21-d25859fe1479">

2023-11-22 14:35 UTC, joaodiaslobo commented
Can you align the inputs in two columns with the same width? I don't really like them misaligned 😅
<img width="535" alt="image" src="https://github.com/cesium/atomic/assets/30907944/153072a8-049c-4327-a641-3e6753640db6">

2024-02-11 15:47 UTC, joaodiaslobo approved these changes

2024-02-11 15:54 UTC, merged