feat: add pagination to all tables
cesium/atomic pull request #375
Opened 2023-08-24 21:12 UTC by joaodiaslobo

2023-08-28 20:50 UTC, MarioRodrigues10 requested changes, later dismissed
Make sure every page is accessible, for example this one:
/organizations/:id returns an error when acessed
![image](https://github.com/cesium/atomic/assets/93675410/3c29a4e9-6192-465c-96ab-e892333e101e)

2023-08-28 20:51 UTC, MarioRodrigues10 commented
Also @joaodiaslobo and @RuiL1904 , do you think would make sense to have a role field in the following table:
![image](https://github.com/cesium/atomic/assets/93675410/f5441779-2e13-4d74-8b08-a99cbdb2366a)

2023-08-28 23:58 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/index.ex
> +  defp list_sessions(id, params) do
```suggestion
  defp list_sessions(id, params \\ %{}) do
```

2023-08-28 23:58 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/index.ex
> +    {:noreply, assign(socket, list_sessions(socket.assigns.current_organization.id, %{}))}
```suggestion
    {:noreply, assign(socket, list_sessions(socket.assigns.current_organization.id))}
```

2023-08-28 23:58 UTC, RuiL1904 commented on lib/atomic_web/live/activity_live/index.ex
> +    {:noreply, assign(socket, list_sessions(socket.assigns.current_organization.id, %{}))}
```suggestion
    {:noreply, assign(socket, list_sessions(socket.assigns.current_organization.id))}
```

2023-08-31 22:45 UTC, RuiL1904 reviewed
![image](https://github.com/cesium/atomic/assets/76881129/06b19722-b291-4bce-b806-a3883e894265)
I'm getting this error while trying to access memberships page.

2023-09-01 19:12 UTC, RuiL1904 submitted a review, later dismissed
Excellent work! 🚀

2023-09-01 22:12 UTC, joaodiaslobo commented
> Also @joaodiaslobo and @RuiL1904 , do you think would make sense to have a role field in the following table: ![image](https://user-images.githubusercontent.com/93675410/263831165-f5441779-2e13-4d74-8b08-a99cbdb2366a.png)

That's certainly something that can be added, in this specific table the only memberships displayed are ones belonging to members, admins and owners. I'll add a new column for this field. 👍

2023-09-01 22:25 UTC, RuiL1904 reviewed
I'm not being able to sort "Requested At" and "Last Update" fields.

2023-09-04 21:48 UTC, RuiL1904 approved these changes, later dismissed

2023-09-05 10:12 UTC, RuiL1904 approved these changes

2023-09-05 11:35 UTC, merged