feat(organzations): improve UI & UX
cesium/atomic pull request #387
Opened 2023-08-26 15:44 UTC by feliciofilipe

![ArcoLinux_2023-08-26_16-43-25](https://github.com/cesium/atomic/assets/55213469/fd563797-8a34-4265-9b06-af948bf4fc1f)
![ArcoLinux_2023-08-26_16-43-16](https://github.com/cesium/atomic/assets/55213469/6c0e4650-03f6-40dc-9bad-808ca2e6ef0e)
![ArcoLinux_2023-08-26_16-43-07](https://github.com/cesium/atomic/assets/55213469/628accb5-e9d8-4a1b-868a-8886a00c6f44)
![ArcoLinux_2023-08-26_16-42-44](https://github.com/cesium/atomic/assets/55213469/73c65277-1314-4e3e-ace2-89ddc31bc78e)
![ArcoLinux_2023-08-26_16-42-34](https://github.com/cesium/atomic/assets/55213469/838cdd25-806a-4e44-b8b5-60f47f2ed62a)

2023-08-26 20:08 UTC, MarioRodrigues10 submitted a review, later dismissed

2023-08-26 20:08 UTC, MarioRodrigues10 commented on lib/atomic/organizations.ex
> +    end
Make sure CeSIUM members , admins and owners can't delete his memberships

2023-08-26 21:10 UTC, feliciofilipe commented on lib/atomic/organizations.ex
> +    end
I'm not understanding

2023-08-27 00:27 UTC, MarioRodrigues10 commented on lib/atomic/organizations.ex
> +    end
```c
membership.role == :follower
``` 
Users with member, admin and owner role can delete their membership.

2023-08-27 02:47 UTC, feliciofilipe commented on lib/atomic/organizations.ex
> +    end
As they should, admins and owners is CeSIUM should be temporary roles

2023-08-28 10:38 UTC, feliciofilipe commented on lib/atomic/organizations.ex
> +    end
@MarioRodrigues10 Make the necessary changes and merge this asap plz :pray:

2023-09-02 22:52 UTC, RuiL1904 submitted a review, later dismissed

2023-09-03 09:43 UTC, MarioRodrigues10 commented
Please note that the whole application is in orange while this feat is in indigo.

2023-09-20 09:43 UTC, danielsp45 commented
Please adjust this so it doesn't alter its size 🙏🏻
<img width="535" alt="image" src="https://github.com/cesium/atomic/assets/46000449/8f646a29-9918-4889-b028-b38d2cf02c76">

2023-09-20 09:47 UTC, danielsp45 commented
This is also happening:
<img width="811" alt="image" src="https://github.com/cesium/atomic/assets/46000449/c39d579b-7e29-4545-9703-902e14bfd4f9">

2023-09-20 09:50 UTC, danielsp45 requested changes
Please fix the CeSIUM box size when the long name is too big and the letters escaping the box when the screen is too narrow 🙏🏻
<img width="811" alt="image" src="https://github.com/cesium/atomic/assets/46000449/f548dc37-cd86-4c37-89ce-d70321705f83">

2023-09-20 11:38 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/show.ex
> +     # |> assign(:time_zone, socket.assigns.time_zone)
```suggestion
```

2023-09-20 11:38 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/show.ex
> +     |> assign(:params, params)
Why is this needed?

2023-09-20 11:38 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/show.ex
> +     |> assign(:mode, "month")
Why is this needed?

2023-09-20 16:15 UTC, danielsp45 requested changes
Also don't forget to remove the indigo in this button:
<img width="713" alt="image" src="https://github.com/cesium/atomic/assets/46000449/aa7f1485-844c-4c03-a9e9-e151320c948f">

2023-09-20 16:16 UTC, danielsp45 commented on priv/repo/seeds/organizations.exs
> +        long_name: "Isto é apenas um teste",
Utilize the Faker.Lorem to generate the names 🙏

2023-09-20 16:21 UTC, danielsp45 commented on lib/atomic_web/live/organization_live/index.ex
> +    case Organizations.list_organizations(Map.put(params, "page_size", 20)) do
Change the number of Orgs you get to 18. Now that we changed the grid to 3 I think 18 Organisations per page are a better fit

2023-09-20 22:34 UTC, RuiL1904 commented on priv/repo/seeds/organizations.exs
> +        long_name: "Isto é apenas um teste",
Actually, we should update the JSON I've created [here](https://github.com/cesium/atomic/pull/407/files).

2023-09-22 10:30 UTC, danielsp45 requested changes, later dismissed
Can you please make sure that this doesn't happen? You could change to `md:grid-cols-2` and maybe cut the long name with "..." in the end for the less common breakpoints. 
![image](https://github.com/cesium/atomic/assets/46000449/1447306b-1cc0-4dff-8415-b0c493209ddd)

2023-09-23 17:27 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/index.html.heex
> +                <%= String.slice(organization.long_name,0..35) <> "..." %>
```suggestion
                <%= maybe_slice_string(organization.long_name, 35) %>
```
Check this function [here](https://github.com/cesium/atomic/blob/030fe0651a3b3d2f2eafa8a3f06145fd1f52fb68/lib/atomic_web/views/helpers.ex#L190).

2023-09-23 17:27 UTC, RuiL1904 commented on priv/repo/seeds/organizations.exs
> +
```suggestion
```

2023-09-23 17:36 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
This code is kinda repeated 🤔

2023-09-23 17:38 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
I'd like to display either the full name or an abbreviated version of it based on the screen size

2023-09-23 17:39 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
Why is the breakpoint on `md`?

2023-09-23 17:44 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
I've tested it, and in mobile it is showing the long name twice 😅

2023-09-23 17:45 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
md is the only breakpoint where the box is resized due to the organization name

2023-09-23 17:46 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
![image](https://github.com/cesium/atomic/assets/93675410/bc851bd3-d39a-4089-ae56-04d9643093fa)
My mobile version is fine :thinking:

2023-09-23 17:48 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
> I've tested it, and in mobile it is showing the long name twice 😅

Solved , thanks for reporting

2023-09-23 18:04 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
But why don't we want to slice the organization long name only on md?

2023-09-23 18:07 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
Because the box are getting resized due to to long names, as @danielsp45 showed in here.
![image](https://github.com/cesium/atomic/assets/93675410/2e19ba42-e88b-477c-bcce-825400414b22)

2023-09-23 19:04 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
Sure, but other breakpoints would also need a `maybe_slice_string`. Organizations can have giant long names 😅

2023-09-23 21:51 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
I tested it with a 60-character limit, and everything appeared to work smoothly.
Should we slice when an organization as more than 60 chars on it's name?

2023-09-24 11:09 UTC, RuiL1904 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
Of course.

2023-09-24 13:48 UTC, MarioRodrigues10 commented on lib/atomic_web/live/organization_live/index.html.heex
> +              </p>
Done :heavy_check_mark:

2023-09-24 14:06 UTC, RuiL1904 approved these changes

2023-09-24 14:19 UTC, merged