Refactor: remove sessions
cesium/atomic pull request #397
Opened 2023-08-28 23:56 UTC by danielsp45

2023-08-31 22:39 UTC, RuiL1904 requested changes
There are a few pages left.
- Calendar (week and month components too)
- Edit Activity
- Show Organization
- Show Department

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/activities/activity.ex
> +    embeds_one :location, Location, on_replace: :delete
```suggestion
    embeds_one :location, Location
```

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/activities/activity.ex
> +    many_to_many :speakers, Speaker, join_through: ActivitySpeaker, on_replace: :delete
```suggestion
    many_to_many :speakers, Speaker, join_through: ActivitySpeaker
```

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/activities/activity.ex
> +    many_to_many :departments, Department, join_through: ActivityDepartment, on_replace: :delete
```suggestion
    many_to_many :departments, Department, join_through: ActivityDepartment
```

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/activities/activity.ex
> +
```suggestion
```

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/activities/activity.ex
> +
```suggestion
```

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/activities/speaker.ex
> +    many_to_many :activities, Activity, join_through: ActivitySpeaker, on_replace: :delete
```suggestion
    many_to_many :activities, Activity, join_through: ActivitySpeaker
```

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/departments.ex
>    end
```suggestion
  def get_department_activities(department_id, opts \\ [preloads: [:activity]]) do
    ActivityDepartment
    |> where([a], a.department_id == ^department_id)
    |> apply_filters(opts)
    |> select([a], a.activity)
    |> Repo.all()
  end
```
I think this should work, but, please, ensure it.

2023-09-02 17:16 UTC, RuiL1904 commented on lib/atomic/organizations/department.ex
> +    many_to_many :activities, Activity, join_through: ActivityDepartment, on_replace: :delete
```suggestion
    many_to_many :activities, Activity, join_through: ActivityDepartment
```

2023-09-03 19:28 UTC, danielsp45 commented on lib/atomic/departments.ex
>    end
I think it maybe should be after, so it applies all the filters in a reduced number of entries.

2023-09-03 20:44 UTC, RuiL1904 approved these changes

2023-09-03 20:52 UTC, merged