refactor: enhance enrollments schema
cesium/atomic pull request #417
Opened 2023-09-14 18:13 UTC by danielsp45

2023-09-15 07:36 UTC, MarioRodrigues10 requested changes, later dismissed
I think we should also change the function names, for example:
`list_enrollments`  to `list_activity_enrollments`  so everything stays under the same context

2023-09-16 16:38 UTC, danielsp45 commented
> I think we should also change the function names, for example:
> 
> `list_enrollments`  to `list_activity_enrollments`  so everything stays under the same context

I think that's a bit redundant because you will do `Activity.list_enrollments()` and then `Event.list_enrollments()`. It will already be self explanatory which one I'm referring to.

2023-09-17 18:54 UTC, RuiL1904 reviewed
Everything looks perfect, but solve the remaining conflicts, please 🙏🏼

2023-09-18 22:15 UTC, RuiL1904 approved these changes

2023-09-19 07:12 UTC, merged