feat: add toggle password to password fields
cesium/atomic pull request #421
Opened 2023-09-17 15:33 UTC by MarioRodrigues10

2023-09-17 16:46 UTC, joaodiaslobo requested changes
Change password inputs to have the same text size as the other inputs and same ring size on focus.  Fix the registration page password inputs to have the same spacing.

Also, the mobile view's elements are not sized properly:

![image](https://github.com/cesium/atomic/assets/30907944/d57da78f-095b-4ea3-b97b-de9188ccf7e4)

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_session/new.html.heex
> +      <div x-data="{ hide: true }" class="flex flex-row items-center justify-center w-full block border border-zinc-300 rounded placeholder-zinc-500 focus-within:z-10 focus-within:border-orange-400 f
```suggestion
      <div x-data="{ hide: true }" class="flex flex-row items-center justify-center w-full block border border-zinc-300 rounded placeholder-zinc-500 focus-within:z-10 focus-within:border-orange-400 focus-within:ring-orange-400 focus-within:ring-1 sm:text-sm">

```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_session/new.html.heex
> +        </div>
```suggestion
          class: "relative w-full border-0 text-zinc-900 rounded appearance-none outline-none focus:ring-0 sm:text-sm"
        ) %>
        <div x-show="hide" x-on:click="hide = false; document.getElementById('user_password').type = 'text';" class="px-2 w-fit cursor-pointer">
          <Ionicons.Filled.eye class="w-5 h-auto fill-zinc-900 hover:fill-black" />
        </div>
        <div x-show="!hide" x-on:click="hide = true; document.getElementById('user_password').type = 'password';" class="px-2 w-fit cursor-pointer">
          <Ionicons.Filled.eye_off class="w-5 h-auto fill-zinc-900 hover:fill-black" />
        </div>
```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_registration/new.html.heex
>            autocomplete: "current-password",
```suggestion
      <div class="flex flex-col items-center justify-center">
        <div x-data="{ hide: true }" class="flex flex-row items-center justify-center w-full block border border-zinc-300 rounded placeholder-zinc-500 focus-within:z-10 focus-within:border-orange-400 focus-within:ring-orange-400 focus-within:ring-1 sm:text-sm">
          <%= label(f, :password, class: "sr-only") %>
          <%= password_input(f, :password,
            required: true,
            placeholder: gettext("Password"),
            autocomplete: "current-password",
```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_registration/new.html.heex
> +          class: "relative w-full border-0 text-zinc-900 rounded appearance-none outline-none focus:outline-none focus:ring-0"
```suggestion
          class: "relative w-full border-0 text-zinc-900 rounded appearance-none outline-none focus:outline-none focus:ring-0 sm:text-sm"
```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_registration/new.html.heex
> +        </div>
```suggestion
        <div x-show="hide" x-on:click="hide = false; document.getElementById('user_password').type = 'text';" class="px-2 w-fit cursor-pointer">
            <Ionicons.Filled.eye class="w-5 h-auto fill-black hover:fill-black" />
          </div>
          <div x-show="!hide" x-on:click="hide = true; document.getElementById('user_password').type = 'password';" class="px-2 w-fit cursor-pointer">
            <Ionicons.Filled.eye_off class="w-5 h-auto fill-black hover:fill-black" />
          </div>
```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_registration/new.html.heex
> +      <span class="text-sm w-full sm:w-96 mx-4 text-red-600"><%= error_tag(f, :password) %></span>
```suggestion
        <span class="text-sm w-full sm:w-96 mx-4 text-red-600"><%= error_tag(f, :password) %></span>
      </div>
```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_registration/new.html.heex
>            autocomplete: "current-password",
```suggestion
      <div class="flex flex-col items-center justify-center">
        <div x-data="{ hide_confirm: true }" class="flex flex-row items-center justify-center w-full block border border-zinc-300 rounded placeholder-zinc-500 focus-within:z-10 focus-within:border-orange-400 focus-within:ring-orange-400 focus-within:ring-1  sm:text-sm">
          <%= label(f, :password_confirmation, class: "sr-only") %>
          <%= password_input(f, :password_confirmation,
            required: true,
            placeholder: gettext("Confirm password"),
            autocomplete: "current-password",
```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_registration/new.html.heex
> +          class: "relative w-full border-0 text-zinc-900 rounded appearance-none outline-none focus:outline-none focus:ring-0"
```suggestion
                      class: "relative w-full border-0 text-zinc-900 rounded appearance-none outline-none focus:outline-none focus:ring-0 sm:text-sm"
```

2023-09-17 16:46 UTC, joaodiaslobo commented on lib/atomic_web/templates/user_registration/new.html.heex
>      </div>
```suggestion
                  <div x-show="hide_confirm" x-on:click="hide_confirm = false; document.getElementById('user_password_confirmation').type = 'text';" class="px-2 w-fit cursor-pointer">
            <Ionicons.Filled.eye class="w-5 h-auto fill-black hover:fill-black" />
          </div>
          <div x-show="!hide_confirm" x-on:click="hide_confirm = true; document.getElementById('user_password_confirmation').type = 'password';" class="px-2 w-fit cursor-pointer">
            <Ionicons.Filled.eye_off class="w-5 h-auto fill-black hover:fill-black" />
          </div>
        </div>
        <span class="text-sm w-full sm:w-96 mx-4 text-red-600"><%= error_tag(f, :password_confirmation) %></span>
      </div>
    </div>
```

2023-09-17 19:10 UTC, RuiL1904 reviewed
Both inputs should occupy the same width as the "Log in" button. Just like it was before 🙏🏼

2023-09-18 08:40 UTC, joaodiaslobo commented
Also, can you add the following CSS code to `app.css` to disable the toggle Microsoft Edge adds to show the password?

```css
/* Hide password reveal button in MS Edge */
::-ms-reveal {
  display: none;
}
```

To avoid this:

<img width="323" alt="image" src="https://github.com/cesium/atomic/assets/30907944/d6274060-5563-4ee0-bc43-197d97c5a74b">

2023-09-23 18:19 UTC, joaodiaslobo approved these changes
Good job! 🚀

2023-09-23 18:20 UTC, merged