fix: enhance board display
cesium/atomic pull request #424
Opened 2023-09-21 17:23 UTC by danielsp45

2023-09-23 11:30 UTC, RuiL1904 commented on lib/atomic_web/live/board_live/index.html.heex
> +                  <AtomicWeb.Components.Board.element user_organization={user_organization} />
```suggestion
                  <Board.element user_organization={user_organization} />
```
Add `alias AtomicWeb.Components.Board` on the Elixir file.

2023-10-03 13:29 UTC, joaodiaslobo requested changes

2023-10-03 13:29 UTC, joaodiaslobo commented on lib/atomic_web/components/board.ex
> +  def element(assigns) do
```suggestion
  def member_bubble(assigns) do
```

2023-10-03 13:29 UTC, joaodiaslobo commented on lib/atomic_web/live/board_live/index.html.heex
> +                  <AtomicWeb.Components.Board.element user_organization={user_organization} />
```suggestion
                  <.member_bubble user_organization={user_organization} />
```

And add the following import to `live/board_live/index.ex`:
```ex
  import AtomicWeb.Components.Board
```

2023-10-03 18:11 UTC, joaodiaslobo approved these changes

2023-10-03 21:41 UTC, merged