feat: memberships export to csv and excel
cesium/atomic pull request #441
Opened 2023-10-10 22:25 UTC by joaodiaslobo

Memberships export functionality to csv or excel.

![image](https://github.com/cesium/atomic/assets/30907944/a8a9a5bc-9f0f-4d54-bc2c-f1c23b5330d2)

![image](https://github.com/cesium/atomic/assets/30907944/3e9e0106-d3cf-46fb-afcd-95f1d5522da9)

2023-10-10 22:54 UTC, MarioRodrigues10 requested changes

2023-10-10 22:54 UTC, MarioRodrigues10 commented on lib/atomic_web/controllers/data_export_controller.ex
> +        |> send_resp(200, data)
```suggestion
    case write_memberships_xlsx(organization_id) do
      {:ok, data} ->
        conn
        |> set_xlsx_response_headers()
        |> send_resp(200, data)

      {:error, reason} ->
        conn
        |> send_resp(500, "Internal Server Error: #{reason}")
    end
```

2023-10-10 23:06 UTC, MarioRodrigues10 requested changes
Also make sure to create some documentation to these functions and add unit tests to test the controller.

2023-10-10 23:06 UTC, MarioRodrigues10 commented on lib/atomic_web/controllers/data_export_controller.ex
> +    |> to_string()
```suggestion
 data =
    [
      "number,name,phone_number,email,created_at"
    ] ++
      Enum.map(memberships, fn membership ->
        [
          membership.number,
          membership.user.name,
          membership.user.phone_number,
          membership.user.email,
          datetime_to_excel(membership.user.inserted_at)
        ]
        |> Enum.join(",")
      end)
    |> Enum.intersperse("\n")
    |> to_string()
    
    
{:ok , data}
```

2023-10-11 09:34 UTC, ruilopesm commented on lib/atomic_web/controllers/data_export_controller.ex
> +    column_names = ["Number", "Name", "Phone Number", "Email", "Created At"]
It would be nice to have this normalized with the columns present on the table. Because adding a column there (on the table) and forgetting to add it here, would lead to a non expected behavior. Do you have any suggestion on how to overcome this problem?

2023-10-11 09:34 UTC, ruilopesm commented on lib/atomic_web/controllers/data_export_controller.ex
> +      (["number,name,phone_number,email,created_at"] ++
Same here.

2023-10-14 17:09 UTC, ruilopesm commented on lib/atomic_web/controllers/data_export_controller.ex
> +  # Generic excel heder styling
```suggestion
  # Generic excel header styling
```

2023-10-18 14:40 UTC, MarioRodrigues10 approved these changes
:rocket:

2023-10-18 14:41 UTC, merged