feat: partners index page
cesium/atomic pull request #442
Opened 2023-10-13 08:13 UTC by MarioRodrigues10

2023-11-10 12:45 UTC, diogogmatos commented
![](https://github.trello.services/images/mini-trello-icon.png) [Partners Index Page](https://trello.com/c/J2R7RFOD/7-partners-index-page)

2024-03-08 01:22 UTC, MarioRodrigues10 commented
The PR is done, although partner show page is looking a bit weird, I accept suggestions to improve it.

2024-03-08 15:38 UTC, joaodiaslobo requested changes
It seems like you didn't use the component used for page layouts. Notice the difference between one of the pages that uses it and yours:
<img width="799" alt="image" src="https://github.com/cesium/atomic/assets/30907944/1eed2abf-6eac-44b4-a20b-b3286a5e7c9b">
<img width="965" alt="image" src="https://github.com/cesium/atomic/assets/30907944/51afea8c-2990-449f-8040-756553b629fa">
This has to be done to make sure everything follows the same design principles such as margins, paddings, typography sizes, etc..
To use it you need to write something like this:
```heex
<.page title="Partners">
  <:actions>
    <%= if not @empty? and @has_permissions? do %>
      <.primary_button url={Routes.partner_new_path(@socket, :new, @current_organization)}>
        <%= gettext("New") %>
      </.primary_button>
    <% end %>
  </:actions>
  <!-- PARTNER INDEX CONTENT HERE -->
<./page>
```

2024-03-08 16:49 UTC, MarioRodrigues10 commented
Thanks for the heads up @joaodiaslobo .
Whats your thoughts on partner show page?

2024-03-11 16:45 UTC, joaodiaslobo requested changes

2024-03-11 16:45 UTC, joaodiaslobo commented on lib/atomic/socials/socials.ex
> +  @optional_fields ~w(instagram facebook twitter youtube tiktok website)a
Should be x, not twitter

2024-03-11 16:45 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/show.html.heex
> +          <a class="text-blue-500" href={@partner.socials.instagram}><%= @partner.socials.instagram %></a>
Please use the link component, and make sure that people only save the social handle on the database, not the whole link. Meaning that you compose the real link here, like this:
```suggestion
          <.link class="text-blue-500" href={"instagram.com/#{@partner.socials.instagram}"}><%= @partner.socials.instagram %></a>
```

2024-03-11 16:45 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/show.html.heex
> +          </svg>
There's probably a better way to save these icons 🤔, leaving them like this makes the code not readable and the icons not really re-usable. I'll try to think of a better solution for this and then I'll update this comment !💪

2024-03-11 16:45 UTC, joaodiaslobo commented on priv/repo/seeds/partners.exs
> +      website: Faker.Internet.url()
```suggestion
      instagram: Faker.Internet.slug(),
      facebook: Faker.Internet.slug(),
      twitter: Faker.Internet.slug(),
      youtube: Faker.Internet.slug(),
      tiktok: Faker.Internet.slug(),
      website: Faker.Internet.slug()
```

2024-03-11 16:45 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/show.ex
> +  import AtomicWeb.Components.{Avatar, Button}
No need to import `Button`, it's already imported globally
```suggestion
  import AtomicWeb.Components.Avatar
```

2024-03-11 17:17 UTC, MarioRodrigues10 commented
@joaodiaslobo  i've already changed what you suggested, i'll wait now for your suggestion for the socials

2024-04-24 14:41 UTC, joaodiaslobo requested changes

2024-04-24 14:41 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/form_component.ex
> +  # lobo
Why this comment? 🤔

2024-04-24 14:44 UTC, MarioRodrigues10 commented on lib/atomic_web/live/partner_live/form_component.ex
> +  # lobo
I don't really know, how that line entered in the code, i guess someone may have typed it in my computer.

2024-06-13 12:07 UTC, joaodiaslobo requested changes
These brand icons should be monochromatic (not colored).

![image](https://github.com/cesium/atomic/assets/30907944/508cc402-2c86-4291-97de-ad578e99754b)

Font Awesome has them available [here](https://fontawesome.com/search?o=r&f=brands), and you can download them as SVGs.

2024-06-13 12:08 UTC, joaodiaslobo requested changes
The related partner boxes are not left aligned with the rest of the elements.

![image](https://github.com/cesium/atomic/assets/30907944/6ad9467b-da4e-49a4-b9a6-b6565ef876eb)

2024-06-13 12:09 UTC, joaodiaslobo requested changes
This doesn't look correct on mobile views.

![image](https://github.com/cesium/atomic/assets/30907944/664b193a-1512-46e6-b85c-7c3f42370b5e)

2024-06-13 12:10 UTC, joaodiaslobo requested changes
Edit partner button should have a pencil icon, not a plus icon.

![image](https://github.com/cesium/atomic/assets/30907944/9afa16e0-9e71-4313-ad65-99b46805af01)

2024-06-13 12:13 UTC, joaodiaslobo commented on lib/atomic/partnerships.ex
> +  def list_partners_by_organization_id(opts) when is_list(opts) do
This is no longer a function that "lists partners by organization id", since now it receives a map of options, maybe change it to `list_partners/1`?

2024-06-17 15:54 UTC, MarioRodrigues10 commented on lib/atomic_web/live/partner_live/show.html.heex
> +                  <img src="/images/instagram.svg" class="h-5 w-5 fill-zinc-400" alt="Instagram" />
```suggestion
                  <img src="/images/instagram.svg" class="h-5 w-5" alt="Instagram" />
```

2024-06-17 16:31 UTC, joaodiaslobo requested changes

2024-06-17 16:31 UTC, joaodiaslobo commented on lib/atomic/organizations/partner.ex
>      field :state, Ecto.Enum, values: @states, default: :active
Can't this be a boolean value?

2024-06-17 16:31 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/show.html.heex
> +                        <Heroicons.map_pin solid class="h-5 w-5 text-zinc-400" />
This should be using the icon component

2024-06-20 15:24 UTC, joaodiaslobo requested changes
Just needs some small adjustments and should be ready to be merged, thanks!

2024-06-20 15:24 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/edit.html.heex
> +    <.live_component module={AtomicWeb.PartnerLive.FormComponent} current_user={@current_user} id={@partner.id || :new} title={@page_title} action={@live_action} partner={@partner} return_to={Routes.
```suggestion
    <.live_component module={AtomicWeb.PartnerLive.FormComponent} id={@partner.id || :new} organization={@current_organization} action={@live_action} partner={@partner} return_to={Routes.partner_index_path(@socket, :index, @current_organization)} />
```

2024-06-20 15:24 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/form_component.ex
> +    organization_id = socket.assigns.current_user.current_organization_id
```suggestion
    organization_id = socket.assigns.organization.id
```

2024-06-20 15:24 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/form_component.ex
> +            <.field type="text" help_text={gettext("A brief description of the partner")} field={f[:description]} placeholder="Description" required />
Shouldn't the description use a text area input?

2024-06-20 15:24 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/form_component.ex
> +              <.field field={location_form[:name]} type="text" placeholder="Location name" help_text={gettext("The name of the location")} required />
```suggestion
              <.field field={location_form[:name]} label="Address" type="text" placeholder="Address" help_text={gettext("Address of the partner")} required />
```

2024-06-20 15:24 UTC, joaodiaslobo commented on lib/atomic/partnerships.ex
>    end
I think this should have a different name, partners don't have banners, they have **picture**s.
So something like `update_partner_picture/3` should work better in this context 👍

2024-07-01 14:41 UTC, joaodiaslobo approved these changes
Good job! 🚀

2024-07-01 14:43 UTC, merged