feat: improve departments view page
cesium/atomic pull request #454
Opened 2024-02-15 17:59 UTC by AfonsoMartins26

Hides collaborators table when there are no collaborators

2024-02-16 23:16 UTC, MarioRodrigues10 requested changes, later dismissed
Looks awesome, just make those changes and it's ready to go :star_struck:

2024-02-16 23:16 UTC, MarioRodrigues10 commented on lib/atomic_web/live/department_live/show.html.heex
> +                        </.link>
Looks like this lines aren't doing anything, could you remove them.
```suggestion

```

2024-02-21 21:57 UTC, ruilopesm approved these changes
Great work! 🧡

2024-02-21 22:01 UTC, MarioRodrigues10 approved these changes
Looks good to me :rocket: :orange_heart:

2024-02-22 15:38 UTC, joaodiaslobo approved these changes
LGTM! 🧡

2024-02-22 15:42 UTC, merged