feat: avatar component
cesium/atomic pull request #457
Opened 2024-02-20 12:07 UTC by joaodiaslobo

Reusable avatar component for users and organizations

2024-02-20 15:25 UTC, ruilopesm commented on lib/atomic_web/components/avatar.ex
> +  attr :type, :atom, values: [:user, :company], default: :user
```suggestion
  attr :type, :atom, values: [:user, :company], default: :user
```
What about organizations?

2024-02-20 15:27 UTC, joaodiaslobo commented on lib/atomic_web/components/avatar.ex
> +  attr :type, :atom, values: [:user, :company], default: :user
Organizations are companies, I chose to call it that name because its also the same look for partner avatars

2024-02-20 17:50 UTC, MarioRodrigues10 requested changes
Avatar at `organization_show_page` is rounded instead of squared.

2024-02-21 21:56 UTC, ruilopesm reviewed
You forgot to replace avatars on `_live_navbar.html.heex` file.

2024-02-21 22:08 UTC, MarioRodrigues10 requested changes
Please replace avatars at:

- Person at `organization_show_page`
- Speaker at  `activity_show_page`  and `activity_index_page`

2024-02-23 15:51 UTC, MarioRodrigues10 approved these changes
:rocket: :orange_heart:

2024-02-23 15:56 UTC, merged