feat: added component primary button and changed necessary heex files
cesium/atomic pull request #458
Opened 2024-02-20 16:25 UTC by FilipeR13

2024-02-20 16:48 UTC, ruilopesm commented on lib/atomic_web/components/button.ex
> +  slot :inner_block, required: true
```suggestion
  slot :inner_block, required: true

```

2024-02-20 17:34 UTC, MarioRodrigues10 requested changes
Run `mix format` in order to pass CI.

2024-02-20 22:50 UTC, MarioRodrigues10 requested changes
This looks awesome :star_struck: , there's only 2 buttons left:

- New Partner button at `partner_index_page`
- New Board member button at `board_index_page` 

Could you update them?
After that it's ready to go !!

2024-02-21 16:22 UTC, MarioRodrigues10 approved these changes
Good job !! :rocket: :orange_heart:

2024-02-21 16:35 UTC, merged