chore: follow suggestions
cesium/atomic pull request #460
Opened 2024-02-20 17:29 UTC by MarioRodrigues10

2024-02-21 22:07 UTC, joaodiaslobo requested changes

2024-02-21 22:07 UTC, joaodiaslobo commented on lib/atomic_web/live/home_live/components/follow_suggestions.ex
> +    doc: "Name of the follow button."
Change the docs

2024-02-21 22:13 UTC, joaodiaslobo requested changes
It seems like the organizations are being re-ordered after following one, it looks kinda odd. Can you take a look into that?

2024-02-21 23:39 UTC, MarioRodrigues10 commented
@joaodiaslobo , I had to refactor a lot of code, so double check everything.
I don't really like the name of the component that i used, so if you have suggestions to name it I have my ears open.

2024-02-22 15:33 UTC, joaodiaslobo requested changes

2024-02-22 15:33 UTC, joaodiaslobo commented on lib/atomic_web/live/home_live/components/organization.ex
> +    doc: "The button placeholder."
```suggestion
  attr :is_following, :bool,
    default: false,
    doc: "Current user follow state for the organization."
```

2024-02-22 15:33 UTC, joaodiaslobo commented on lib/atomic_web/live/home_live/components/organization.ex
> +defmodule AtomicWeb.HomeLive.Components.FollowSuggestions.Organization do
```suggestion
defmodule AtomicWeb.HomeLive.Components.FollowSuggestions.Suggestion do
```

2024-02-22 15:33 UTC, joaodiaslobo commented on lib/atomic_web/live/home_live/components/follow_suggestions.ex
> +  use AtomicWeb, :live_component
Can this be a functional component?

2024-02-23 16:04 UTC, joaodiaslobo approved these changes, later dismissed
LGTM! 🤘

2024-02-23 16:08 UTC, joaodiaslobo approved these changes
Still LGTM! 🤘

2024-02-23 16:08 UTC, MarioRodrigues10 commented
@joaodiaslobo  i had to rebase due to recent changes, can you approve again? Thanks :pray:

2024-02-23 16:09 UTC, merged