refactor: department pages
cesium/atomic pull request #470
Opened 2024-02-24 02:32 UTC by joaodiaslobo

2024-04-15 09:21 UTC, MarioRodrigues10 requested changes

2024-04-15 09:21 UTC, MarioRodrigues10 commented on lib/atomic_web/live/department_live/show.html.heex
> +                <%= for collaborator <- @all_collaborators |> Enum.take(18) do %>
Use `limit` in query instead of Enum.take
```suggestion
                <%= for collaborator <- @all_collaborators |> Enum.take(18) do %>
```

2024-04-15 09:21 UTC, MarioRodrigues10 commented on lib/atomic_web/live/department_live/show.html.heex
> +                    </.button>
In mobile version should have more spacing between them.
Example:
![image](https://github.com/cesium/atomic/assets/93675410/1ef86178-23a0-4731-9ac1-9a5f91bda342)

2024-04-15 09:21 UTC, MarioRodrigues10 commented on lib/atomic_web/live/department_live/show.html.heex
> +                <.pagination items={@collaborators} meta={@meta} params={@params} class="flex w-full items-center justify-between border border-t-0 pt-2" />
Pagination isn't correct in mobile version.
![image](https://github.com/cesium/atomic/assets/93675410/6905f169-a867-41c1-929a-3298437ac29b)

2024-04-15 09:21 UTC, MarioRodrigues10 commented on lib/atomic_web/live/department_live/form_component.ex
> +            <.live_component module={ImageUploader} id="uploader" uploads={@uploads} target={@myself} />
You should indicate the dimensions of the banner

2024-04-15 09:37 UTC, MarioRodrigues10 requested changes

2024-04-15 09:37 UTC, MarioRodrigues10 commented on lib/atomic/organizations/collaborator.ex
> +  @optional_fields ~w(accepted accepted_at)a
Accepted should be required, even if the value is false

2024-04-15 09:37 UTC, MarioRodrigues10 commented on lib/atomic_web/live/department_live/components/department_card.ex
> +          <%= for person <- @collaborators |> Enum.take(4) do %>
Use `limit` in query instead of Enum.take

2024-04-15 09:37 UTC, MarioRodrigues10 commented on priv/repo/migrations/20230880102641_create_collaborators.exs
> +      add :department_id, references(:departments, on_delete: :delete_all, type: :binary_id),
You sure?
Don't we wanna keep the history if a collaborator is removed from the department?

2024-04-15 09:37 UTC, MarioRodrigues10 commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +        {:noreply, socket |> assign(:action_modal, nil)}
Couldn't you wrap all this send's into a function like a notify
```ex
defp notify_result(socket, status, message) do
  send(self(), {:change_collaborator, %{status: status, message: message}})
  {:noreply, assign(socket, :action_modal, nil)}
end
```

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic/uploaders/banner.ex
> +  alias Atomic.Organizations.Department
```suggestion
  use Atomic.Uploader

  alias Atomic.Organizations.Department
```

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +          <p>Requested <%= Timex.from_now(@collaborator.inserted_at) %></p>
Why not use the `relative_datetime` util function here?

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +            <p>Not accepted</p>
```suggestion
            <p><%= gettext(Not accepted) %></p>
```

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +          <p>Requested <%= Timex.from_now(@collaborator.inserted_at) %></p>
```suggestion
          <p><%= gettext(Requested) %> <%= Timex.from_now(@collaborator.inserted_at) %></p>
```

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +        )
I guess you shouldn't be passing the department name to the `gettext` call, as there would not be a point to also translate it in the future.

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/department_live/components/department_banner_placeholder.ex
> +defmodule AtomicWeb.DepartmentLive.Components.DepartmentBannerPlaceholder do
Why not create a more generic component? We could reuse it on organization show page 💡

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/department_live/components/department_card.ex
> +        </div>
```suggestion
        <ul class="min-h-8 mt-4 mb-2 flex flex-row -space-x-1">
          <%= for person <- @collaborators |> Enum.take(4) do %>
          	<li>
          		<.avatar name={person.user.name} size={:xs} color={:light_gray} class="ring-1 ring-white" />
            </li>
          <% end %>
          <%= if length(@collaborators) > 4 do %>
          	<li>
            	<.avatar name={"+#{length(@collaborators) - 4}"} size={:xs} auto_generate_initials={false} color={:light_gray} class="ring-1 ring-white" />
            </li>
          <% end %>
        </ul>
```
Just if this doesn't mess with the styling 😄

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/department_live/edit.ex
> +        )
Same as before.

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/department_live/edit.html.heex
> +    "New Department"
```suggestion
    <%= gettext("New Department") %>
```
There are tons of strings, throughout the whole code base, not internationalized. We should probably take care of them on other PR? What do you think? 🙏🏼

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/department_live/form_component.ex
> +    <div>
Imagine having fragments in Phoenix 👀

2024-04-15 12:19 UTC, ruilopesm commented on lib/atomic_web/live/department_live/form_component.ex
> +          <.button size={:md} color={:white} icon={:cube}>Save Changes</.button>
The `button` component is missing a `type` attribute or did you forgot to put it here (with value `submit`, in this case)?

2024-04-15 14:05 UTC, joaodiaslobo commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +        )
In this context, the only thing that will be translated is the text, not the department name. The department name is only passed to the `gettext` function so that a specific translation can change the department name location inside the string.
An example translation would be:
"Se esta pessoa for removida do %{department_name}, deixará de ter accesso ao mesmo."
This is called Interpolation, and is explained [here](https://hexdocs.pm/gettext/Gettext.html#module-interpolation)

2024-04-15 14:06 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/edit.html.heex
> +    "New Department"
Good idea! 💡 Better do this now than later, when there are tons of strings in the codebase.

2024-04-15 14:13 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/components/department_card.ex
> +        </div>
Good call!

2024-04-15 14:29 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/components/department_banner_placeholder.ex
> +defmodule AtomicWeb.DepartmentLive.Components.DepartmentBannerPlaceholder do
Good idea 💡, will do.

2024-04-15 14:42 UTC, ruilopesm commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +        )
Thanks for the info 🤝

2024-04-15 14:45 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/form_component.ex
> +    <div>
Would be a nice addition tbh, but for now, this will have to do. ([open a PR](https://github.com/phoenixframework/phoenix/compare) :shipit:)

2024-04-15 14:52 UTC, joaodiaslobo commented on priv/repo/migrations/20230880102641_create_collaborators.exs
> +      add :department_id, references(:departments, on_delete: :delete_all, type: :binary_id),
History will only be kept for archived departments. If an organization wants to keep the data of an outdated department they can do it by archiving it. 💡
Deleting is **permanent**.

2024-04-15 14:52 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/form_component.ex
> +          <.button size={:md} color={:white} icon={:cube}>Save Changes</.button>
Since the `button` is inside a form, it automatically turns into a `submit` type.  
But, for better DX, I will specify the `type`. Thanks!

2024-04-15 15:18 UTC, joaodiaslobo commented on lib/atomic_web/live/collaborator_live/form_component.ex
> +        {:noreply, socket |> assign(:action_modal, nil)}
Very good idea!

2024-04-15 15:23 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/components/department_card.ex
> +          <%= for person <- @collaborators |> Enum.take(4) do %>
This is the component context, no queries in this file.
In the parent though, the collaborators are fully fetched in order to get the number of collaborators (displayed in the picture below).
![image](https://github.com/cesium/atomic/assets/30907944/90b6ec00-3c2e-40cc-8529-1aece591a2c3)
As such, for now, I will keep it this way. Don't really see any optimization in creating two queries, one for the count and one for the collaborators.

2024-04-15 15:26 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/show.html.heex
> +                <.pagination items={@collaborators} meta={@meta} params={@params} class="flex w-full items-center justify-between border border-t-0 pt-2" />
Can't really replicate this problem. 🤔
In theory, (currently) the screen resolution shouldn't be altering the number of items displayed. Even so, if there is a problem there, it probably has to do with either the `pagination` or `table` components.

2024-04-15 15:32 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/show.html.heex
> +                    </.button>
This is a problem for phones that have a width resolution of less than 310 pixels.
I will not be fixing problems related to uncommon resolutions like this one.

![image](https://github.com/cesium/atomic/assets/30907944/b7237b32-ee3e-40e5-9b4e-ac7ec12c6acf)

2024-04-15 15:44 UTC, MarioRodrigues10 commented on lib/atomic_web/live/department_live/show.html.heex
> +                    </.button>
In case this is in a wider resolution, for example 410 px

2024-04-15 16:20 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/show.html.heex
> +                <%= for collaborator <- @all_collaborators |> Enum.take(18) do %>
I need all the collaborators for other purposes (like counting and such), so for now, I will not alter the query.

2024-04-15 16:20 UTC, joaodiaslobo commented on lib/atomic_web/live/department_live/form_component.ex
> +            <.live_component module={ImageUploader} id="uploader" uploads={@uploads} target={@myself} />
Good idea 💡

2024-04-17 13:39 UTC, MarioRodrigues10 requested changes
An email should be send when an user applies to be a collaborator and when it's accepted.

2024-04-18 01:02 UTC, MarioRodrigues10 approved these changes
[Awesome :rocket: ](https://www.youtube.com/watch?v=2a8PgqWrc_4&ab_channel=TravisScottVEVO)

2024-04-18 01:05 UTC, merged