feat: added column enrolled to Activities
cesium/atomic pull request #471
Opened 2024-02-24 20:06 UTC by FilipeR13

2024-03-03 00:21 UTC, ruilopesm reviewed
A few things:

- Max enrollments check on activity show page is not working properly, not showing the "Enroll" button even thought the activity has available space
- An _unenrollment_ its not taking effect on the `enrolled` field of its activity, it should decrease it, in this case

2024-03-04 22:30 UTC, FilipeR13 commented
For performance reasons, I decided to keep the `:enrolled` atom to increase the speed with which the page reloads and displays this same field. This is because, in this way, in the `reload()` method, the activity doesn't need to reload as a whole, but only the enrolled variable.

2024-03-14 12:01 UTC, danielsp45 commented on lib/atomic/activities/activity.ex
> +        validate_enrollments_values(changeset.data.enrolled, maximum, changeset)
Why are you using `changeset.data.enrolled` instead of `enrolled` defined on the line 131?

2024-03-14 12:01 UTC, danielsp45 commented on lib/atomic/activities/activity.ex
> +        validate_enrollments_values(enrolled, changeset.data.maximum_entries, changeset)
Same question as the previous comment

2024-03-14 12:02 UTC, danielsp45 requested changes, later dismissed
Please merge with the `develop` branch 🙏🏻

2024-03-14 14:16 UTC, FilipeR13 commented on lib/atomic/activities/activity.ex
> +        validate_enrollments_values(changeset.data.enrolled, maximum, changeset)
Here I followed the same logic that its used on function `validate_entries`  on line 74

2024-03-14 22:15 UTC, ruilopesm commented on lib/atomic/activities.ex
>    end
I think we don't need this function anymore.

2024-03-15 16:22 UTC, ruilopesm commented on lib/atomic/activities/activity.ex
> +        validate_enrollments_values(changeset.data.enrolled, maximum, changeset)
We should think on how to simplify both functions logic. For now, let's stick with this 🙏🏼

2024-03-15 16:26 UTC, ruilopesm commented on lib/atomic_web/live/activity_live/show.ex
> +    |> assign(:enrolled, Activities.get_activity!(socket.assigns.id).enrolled)
Instead of fetching the whole activity, add a named parameter, to `reload` function, like `action: :enroll` (or `action: :uneroll`) that would increment or decrement `enrolled` value accordingly. Then, change its call on `handle_info/2` 💡

2024-03-15 22:44 UTC, ruilopesm approved these changes
What a great work 🙌🏼

2024-03-15 22:55 UTC, merged