feat: dropdown component
cesium/atomic pull request #483
Opened 2024-03-09 23:46 UTC by MarioRodrigues10

The component is implemented at calendar page.

2024-03-11 17:16 UTC, joaodiaslobo requested changes

2024-03-11 17:16 UTC, joaodiaslobo commented on lib/atomic_web/components/dropdown.ex
There's no need for the component to have types such as `button` or `avatar`. 
Ideally, we would have something like this:
```html
<.dropdown ...>
    <!-- CONTENT HERE (avatar as an example) -->
    <.avatar ... />
<.dropdown/>
```
Where you put your content in the inner block of the dropdown component

2024-03-11 17:16 UTC, joaodiaslobo commented on lib/atomic_web/components/dropdown.ex
> +      <button id={"dropdown-#{assigns.label}"} type="button" phx-hook="Dropdown" class="inline-flex h-10 w-10 justify-center rounded-3xl border border-gray-300 bg-white px-4 py-2 text-sm font-medium
No need for hooks, use [LiveView JS](https://hexdocs.pm/phoenix_live_view/0.19.5/Phoenix.LiveView.JS.html#toggle_attribute/1)!
```suggestion
      <button id="dropdown-button" type="button" phx-click={JS.toggle(to: "#dropdown-#{assigns.label}", in: "block", out: "hidden")} class="inline-flex justify-center rounded border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50">
```

2024-03-11 17:16 UTC, joaodiaslobo commented on assets/js/app.js
> +
```suggestion
```

2024-03-18 16:15 UTC, joaodiaslobo requested changes

2024-03-18 16:15 UTC, joaodiaslobo commented on assets/js/app.js
> +
Unused
```suggestion
```

2024-03-18 16:15 UTC, joaodiaslobo commented on lib/atomic_web/components/calendar/calendar.ex
> +                    </button>
Use the available `button` component

2024-03-18 16:15 UTC, joaodiaslobo commented on lib/atomic_web/templates/layout/_live_navbar.html.heex
> +              </button>
Use the available `button` component

2024-03-18 16:15 UTC, joaodiaslobo commented on lib/atomic_web/templates/layout/_live_navbar.html.heex
> +                    </svg>
Why an svg in the middle of the code? Use the `icon` component

2024-03-18 16:15 UTC, joaodiaslobo commented on lib/atomic_web/live/membership_live/index.html.heex
> +        </button>
Use the available `button` component

2024-03-18 16:15 UTC, joaodiaslobo commented on storybook/components/dropdown.story.exs
> +          type: :button,
Dropdown no longer has type
```suggestion
```

2024-03-18 16:15 UTC, joaodiaslobo commented on storybook/components/dropdown.story.exs
> +          type: :avatar,
Dropdown no longer has type
```suggestion
```

2024-03-18 16:15 UTC, joaodiaslobo commented on lib/atomic_web/components/dropdown.ex
> +  attr :image, :string, default: "", doc: "The image of the dropdown."
This looks unused, but not sure 🤔
```suggestion
```

2024-03-18 17:09 UTC, ruilopesm commented on assets/js/app.js
> +
```suggestion
```

2024-03-18 17:11 UTC, ruilopesm commented on lib/atomic_web/live/membership_live/index.ex
> +  import AtomicWeb.Components.Dropdown
```suggestion
  import AtomicWeb.Components.Dropdown

```

2024-03-18 17:15 UTC, ruilopesm commented on lib/atomic_web/components/calendar/calendar.ex
> +                      <.icon name={:chevron_down} solid class="-mr-1 ml-2 h-5 w-5" />
I think this should be a slot called for instance `wrapper` and defined by the caller.
The component would, then, be used like so:
```elixir
<.dropdown ...>
  <:wrapper>
    # content
  </:wrapper>
</.dropdown>
```
Items could also be rendered like this - it would lead to an easier way to add custom styling to them 💡

2024-03-18 17:16 UTC, ruilopesm commented on lib/atomic_web/components/dropdown.ex
> +  use AtomicWeb, :component
```suggestion
  use Phoenix.Component
```
Ask @joaodiaslobo why :milady:

2024-03-18 17:16 UTC, ruilopesm commented on storybook/components/dropdown.story.exs
> +  end
Add more variations 👀

2024-03-18 20:59 UTC, joaodiaslobo commented on lib/atomic_web/components/calendar/calendar.ex
> +                      <.icon name={:chevron_down} solid class="-mr-1 ml-2 h-5 w-5" />
Why create a specific slot for this instead of using the inner block? I think this only adds unneeded complexity to the component 🤔

2024-03-18 21:04 UTC, ruilopesm commented on lib/atomic_web/components/calendar/calendar.ex
> +                      <.icon name={:chevron_down} solid class="-mr-1 ml-2 h-5 w-5" />
Because the term inner block is misleading in this context. Usually, inner blocks are meant to render content inside the component structure. However, here, the inner block is being used as a wrapper of the component.

2024-03-18 21:04 UTC, joaodiaslobo requested changes

2024-03-18 21:04 UTC, joaodiaslobo commented on lib/atomic_web/components/calendar/calendar.ex
> +                      <.icon name={:chevron_down} solid class="-mr-1 ml-2 h-5 w-5" />
btw, you can actually add the icon via the button component thought the following attributes:
```suggestion
                    <.button color={:white} icon={:chevron_down} icon_position={:right} icon_variant={:solid}>
                      <%= if @mode == "month" do %>
                        <%= gettext("Month view") %>
                      <% else %>
                        <%= gettext("Week view") %>
                      <% end %>
```

2024-03-18 21:05 UTC, joaodiaslobo commented on lib/atomic_web/components/calendar/calendar.ex
> +                      <.icon name={:chevron_down} solid class="-mr-1 ml-2 h-5 w-5" />
Makes sense, thank you! 💡

2024-03-19 17:54 UTC, ruilopesm commented on lib/atomic_web/components/dropdown.ex
> +  slot :wrapper, required: true, doc: "Slot for the body content of the dropdown."
```suggestion
  slot :wrapper, required: true, doc: "Slot to be rendered as wrapper of the dropdown. For example, a custom button."
```

2024-03-19 22:22 UTC, ruilopesm commented on lib/atomic_web/components/dropdown.ex
> +    </div>
```suggestion
    <div class="relative inline-block text-left" phx-click={JS.toggle(to: "##{@id}", in: "block", out: "hidden")} phx-click-away={JS.hide(to: "##{@id}")}>
      <%= render_slot(@wrapper) %>
      <div id={@id} class={"#{if @orientation == :down, do: "origin-top-right top-full", else: "origin-bottom-right bottom-full"} absolute right-0 z-10 mt-2 hidden w-56 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5"}>
        <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
          <%= for item <- @items do %>
            <a href={item.link} class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">
              <%= item.name %>
            </a>
          <% end %>
        </div>
      </div>
    </div>
```

2024-03-20 09:45 UTC, ruilopesm reviewed
User dropdown is a bit weird for me 😅
Apart from that, great work! 🙌🏼

![image](https://github.com/cesium/atomic/assets/76881129/6080519e-bd79-475e-9856-66719cdfc439)

2024-03-20 16:59 UTC, joaodiaslobo approved these changes
Good job! 🚀

2024-03-20 16:59 UTC, merged