fix: log out functionality
cesium/atomic pull request #506
Opened 2024-06-17 15:07 UTC by Afonso-santos

The log out functionality didn't work. Now I change the route  and it's work

2024-06-17 15:11 UTC, ruilopesm requested changes, later dismissed
This should actually be a `delete`. You need to change the link that is leading to this endpoint to have a `method="delete"` attribute 😄

2024-06-20 16:36 UTC, joaodiaslobo commented on lib/atomic_web/templates/layout/_live_navbar.html.heex
> +                  %{name: "Your profile", link: Routes.profile_show_path(@socket, :show, @current_user), method: "get"},
You can now remove the `method` value from this map entry, since `"get"` is the default one.
```suggestion
                  %{name: "Your profile", link: Routes.profile_show_path(@socket, :show, @current_user)},
```

2024-06-20 16:37 UTC, joaodiaslobo requested changes
.

2024-06-20 20:16 UTC, joaodiaslobo approved these changes
Nice work, thanks!! 🚀

2024-06-25 16:03 UTC, merged