refactor: improve calendar performance and style
cesium/atomic pull request #518
Opened 2024-08-08 02:00 UTC by nunom27

2024-08-29 12:50 UTC, ruilopesm reviewed
Week view, in mobile, is not showing events, for some reason 🤔

2024-08-29 16:23 UTC, nunom27 commented
> Week view, in mobile, is not showing events, for some reason 🤔

Do you actually follow the organization? You can try unfollowing and following the organization that has the activity again. I believe the seeds that makes generated users follow organizations is a bit broken, because the button shows up as following when the organization has 0 followers.

Also, does the same activity show up in any other view? For me it seems to be working.

2024-08-29 16:28 UTC, ruilopesm commented
@nunom27 I can see activities properly while on a desktop dimensions. After resizing the screen to mobile, activities do not show anymore.

I guess we'll have to wait until someone try to reproduce it 😅

2024-09-01 07:31 UTC, joaodiaslobo commented
Can't reproduce it on my side @ruilopesm . 🤔

https://github.com/user-attachments/assets/7f3060c7-4476-4fad-a89c-6bb3316bc82f

2024-09-01 20:34 UTC, MarioRodrigues10 commented
It works on my side, but looks a little bit odd on my side.
![image](https://github.com/user-attachments/assets/a5e49e51-d2ae-4a3f-b4b2-eecbfe584a3b)
![image](https://github.com/user-attachments/assets/a5972646-fd6b-49fa-8c68-743856ccab6d)

2024-09-02 09:30 UTC, nunom27 commented
@MarioRodrigues10 That happened due to the activity starting at 23:35, so it only takes 5 rows until midnight (each row represents 5 minutes intervals). I can try, however, to put the title right in front of the time on those cases, so that it doesn't look as odd.

2024-09-02 13:56 UTC, ruilopesm commented
It's properly working for me now. I might have tested it wrongly 😅

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/month.ex
> +                  Open activity
```suggestion
                  <%= gettext("Open activity") %>
```

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/month.ex
> +                <.link navigate={Routes.activity_index_path(AtomicWeb.Endpoint, :index)} class="bg-primary-600 flex-none self-center rounded-md px-3 py-2 font-semibold text-white hover:bg-primary-500
Why is this link going to the index page? Anyways, we already have a link covering the whole card, so I guess we wouldn't need a link here.

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/month.ex
> +
Could you document this function with a nice description and useful examples? I know it's private, but documentation would be nice for future contributors 👀

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/month.ex
> +        {"bg-zinc-50 text-zinc-500", assigns.current_date.month != date.month}
You can simply do this and ditch the use of that `class_list` function:
```html
<div class={["relative py-2 ...", assigns.current_date.month == date.month && "bg-white", ...]}>
    ....
</div>
```

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/month.ex
> +        <% end %>
There's a new short syntax for cases like this (same for other places, if you prefer it like so)
```
<li :if={Enum.count(get_date_activities(@activities, @date)) > 2} class="...">
```

<hr>

Also, would you consider this calculation heavy? If so, prefer to assign it before rendering the template, by calculating it only once (you are using it at least twice).

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/month.ex
>            end}"
This is kinda confusing for a reader. Isn't there a better way to present it by using the syntax I've shown you before? 😄

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/week.ex
> +          <div class={"#{if width != 1 do "sm:hover:z-10 sm:hover:w-max sm:max-w-[117px]" end} group absolute inset-1 flex flex-col overflow-x-hidden rounded-md bg-orange-50 p-2 text-xs leading-5 hov
This is a known pitfall when using heex templates. Learn more about it [here](https://hexdocs.pm/phoenix_live_view/assigns-eex.html#pitfalls).

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/components/calendar/week.ex
>    end
Would you mind documenting these 3 functions too? 🥺

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/live/calendar_live/show.html.heex
> +                  <% _ -> %>
Prefer to use an `if`, instead of a `case` here.

2024-09-02 14:21 UTC, ruilopesm commented on lib/atomic_web/views/calendar_utils.ex
>    use Phoenix.HTML
Shouldn't this module be solely on the scope of the calendar? Or is it being used on other places?

2024-09-19 17:25 UTC, joaodiaslobo requested changes

2024-09-19 17:25 UTC, joaodiaslobo commented on lib/atomic_web/live/calendar_live/components/week.ex
> +    ]
```suggestion
    0..23 |> Enum.map(fn n -> "#{n}H" end)
```

2024-09-19 18:11 UTC, joaodiaslobo approved these changes
Looks great!! 🎉📆

2024-09-19 18:11 UTC, merged