refactor: sidebar
cesium/atomic pull request #526
Opened 2024-08-22 18:20 UTC by MarioRodrigues10

## Description
The purpose of this PR is to refactor the sidebar, since it was using alpine and other outdated stuff.

## Related Issues
N/A

## Steps to reproduce or test
- mix phx.server
- Open at localhost:4000
- And see the sidebar in desktop and mobile views

2024-08-22 18:34 UTC, ruilopesm commented on lib/atomic_web.ex
> +      import AtomicWeb.Components.Sidebar
This `import` will be injected into every view and that's not ideal. I would suggest you to reference sidebar's component by its full namespace. In the future, we can migrate our app to use the newest templates creation and then import this namespace there 🙌🏼

2024-08-22 18:34 UTC, ruilopesm commented on lib/atomic_web/components/sidebar.ex
> +  attr :current_organization, :map, required: true
Actually, these maps are structs, so we can type them using `User` and `Organization`, respectively, instead of just `:map` 😄

2024-08-22 18:36 UTC, ruilopesm commented on lib/atomic_web/components/sidebar.ex
> +        name: "Your profile",
```suggestion
        name: gettext("Your profile"),
```
Since you are on this 👀

2024-08-22 18:36 UTC, ruilopesm commented on lib/atomic_web/components/sidebar.ex
> +      %{name: "Sign out", link: Routes.user_session_path(AtomicWeb.Endpoint, :delete)}
```suggestion
      %{name: gettext("Sign out"), link: Routes.user_session_path(AtomicWeb.Endpoint, :delete)}
```

2024-08-22 18:38 UTC, ruilopesm reviewed
Nice refactor. Just check my review and it's ready to merge.

Btw, I'm thinking that we need to find a better way to organize our components under the `components` folder. It's not a big deal, but it's starting to be a bit messy 😅

2024-08-22 20:15 UTC, MarioRodrigues10 commented on lib/atomic_web/components/sidebar.ex
> +  attr :current_organization, :map, required: true
Unfortunately non of those can be typed since sometimes they're value is nil

2024-09-01 07:15 UTC, joaodiaslobo requested changes
Why is the user dropdown not aligned to the bottom anymore? Is this intended?

![image](https://github.com/user-attachments/assets/ecf11466-8a18-4a1f-9d7e-cad37c418fdb)

2024-09-01 07:15 UTC, joaodiaslobo commented on lib/atomic_web/components/sidebar.ex
> +  end
The mobile sidebar animation looks very wrong. 🤔

https://github.com/user-attachments/assets/44f1e21b-9603-4c77-8bb0-af9451e723e2

2024-09-01 15:09 UTC, joaodiaslobo commented on lib/atomic_web/components/sidebar.ex
> +        {"ease-in duration-1000", "transform translate-x-0", "transform -translate-x-full"}
```suggestion
        {"transition ease-in-out duration-300 transform", "-translate-x-full", "translate-x-0"}
```

2024-09-01 15:10 UTC, joaodiaslobo requested changes
Also, make sure that when the user clicks on the dark area on mobile, the sidebar closes.

2024-09-01 15:11 UTC, joaodiaslobo commented on lib/atomic_web/components/sidebar.ex
> +        {"ease-in duration-1000", "transform translate-x-0", "transform -translate-x-full"}
This fixes the problem with the closing animation

2024-09-01 15:11 UTC, MarioRodrigues10 commented
Thanks @joaodiaslobo  🙌 

I removed a lot of bloat from div classes and somehow i moved the user up in the sidebar, I'll get that fixed today

2024-09-08 18:37 UTC, joaodiaslobo commented on lib/atomic_web/components/sidebar.ex
> +      <% end %>
Can this be a `<.link>` ?

2024-09-09 17:17 UTC, joaodiaslobo approved these changes
Nice refactor, thanks!

2024-09-09 17:17 UTC, merged