feat: initial profile layouts
cesium/atomic pull request #528
Opened 2024-09-10 16:28 UTC by AfonsoMartins26

2024-10-03 18:29 UTC, MarioRodrigues10 submitted a review, later dismissed

2024-10-03 18:29 UTC, MarioRodrigues10 commented on lib/atomic/accounts.ex
> +    |> IO.inspect()
```suggestion
    |> IO.inspect()
```

2024-10-03 18:29 UTC, MarioRodrigues10 commented on lib/atomic_web/live/profile_live/show.html.heex
> +          </div>
Since this is being used in multiple places please create a component

2025-03-18 23:40 UTC, joaodiaslobo requested changes

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/form_component.html.heex
> +          <.field field={f[:slug]} type="text" placeholder="User Name" class="w-full" />
```suggestion
          <.field field={f[:slug]} type="text" placeholder="Username" class="w-full" />
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/show.html.heex
> +              <p class="py-2">No organizations found.</p>
```suggestion
              <p class="py-2">{gettext("No organizations found.")}</p>
```

2025-03-18 23:40 UTC, joaodiaslobo commented on public/team.json
Remove this file.

2025-03-18 23:40 UTC, joaodiaslobo commented on public/partners.yml
Remove this file.

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/show.html.heex
> +                <dt class="text-sm font-medium text-zinc-500">Phone</dt>
```suggestion
                <dt class="text-sm font-medium text-zinc-500">{gettext("Phone")}</dt>
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/show.html.heex
> +                <dt class="text-sm font-medium text-zinc-500">Email</dt>
```suggestion
                <dt class="text-sm font-medium text-zinc-500">{gettext("Email")}</dt>
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/form_component.html.heex
> +      <.button size={:md} color={:white} icon="hero-cube">Save</.button>
Don't really like the button icon, but I also don't have a suggestion. Maybe remove it completely?
```suggestion
      <.button size={:md} color={:white}>{gettext("Save")}</.button>
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/form_component.html.heex
> +                <p class="py-2">No organizations found.</p>
```suggestion
                <p class="py-2">{gettext("No organizations found.")}</p>
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/form_component.html.heex
> +        <% end %>
```suggestion
        <%= if @user do %>
          <.image_uploader id="banner-picture" class="h-64 w-full object-cover" image_class="h-[290px] w-full" upload={@uploads.banner} icon="hero-photo" memory_unit="MB" image={Uploaders.Banner.url({@user.banner, @user}, :original, signed: true)} />
        <% else %>
          <.gradient class="h-64 w-full bg-center object-cover" seed={@user.id} />
        <% end %>
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/form_component.ex
> +  alias Atomic.Organizations
```suggestion
  alias Atomic.{Accounts, Organizations}
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/live/profile_live/form.html.heex
> +          <.icon name="hero-archive-box-solid" class="mr-2 -ml-1 h-5 w-5" /> Save
```suggestion
          <.icon name="hero-archive-box-solid" class="mr-2 -ml-1 h-5 w-5" /> {gettext("Save")}
```

2025-03-18 23:40 UTC, joaodiaslobo commented on lib/atomic_web/components/image_uploader.ex
> +                  <div class="text-lightMuted flex flex-col items-center gap-2 dark:text-darkMuted">
These classes don't exist, please replace them to fit this app.

2025-04-30 18:01 UTC, joaodiaslobo approved these changes
Awesome!! 🤘🚀

2025-04-30 18:02 UTC, merged