Jc/improve announcements
cesium/atomic pull request #530
Opened 2024-09-11 11:22 UTC by JoaoCoelho2003

![image](https://github.com/user-attachments/assets/f5e9f436-069e-496b-b20f-987d8f6ef721)
![image](https://github.com/user-attachments/assets/e41b5fde-0926-44dc-a6de-bfb9c077be9f)
![image](https://github.com/user-attachments/assets/1ac4f2c2-038a-4dea-b73e-6706c74465a2)

Updated all the pages that involve announcements

2024-09-11 16:15 UTC, ruilopesm reviewed
There's a lack of padding on every page. Make sure the padding obeys the one _imposed_ by the `page` component. In the future, we should make page's body be padded automatically 💡

2024-09-12 18:48 UTC, FilipeR13 commented
I think it would be cool if the show page followed the same design as the edit/new announcement page when there’s an image to display. What do you think?

2024-09-13 23:18 UTC, MarioRodrigues10 commented
We can have 2 approaches for this scenario:
![image](https://github.com/user-attachments/assets/3d63c4a9-135e-4202-8800-bee3e5b5fa40)

We either limit the characters at index page and if the user wants the full information should open it and see the whole announcement context, or we can keep the whole text and remove the show page since won't be necessary anymore.


Which one do you like more @JoaoCoelho2003 ?

I would also like your input for this case @joaodiaslobo @ruilopesm . :raised_hands:

2024-09-13 23:25 UTC, JoaoCoelho2003 commented
I personally prefer limiting the number of lines shown per announcement on the respective pages @MarioRodrigues10.

2024-09-13 23:28 UTC, joaodiaslobo commented
@MarioRodrigues10 
> I would also like your input for this case @joaodiaslobo @ruilopesm . 🙌

Keeping the whole text in the feed is definitely not the way to go but I also don't think we should limit what the organizations can write way too much (there still needs to exist a limit, but a bigger one). 
Maybe we should truncate the text on the post and allow the users to see the full content in the show page by clicking on the it.

2024-09-13 23:32 UTC, MarioRodrigues10 commented
@joaodiaslobo There's already a lot of text being truncated at the application in different ways, in order to achieve that I think @JoaoCoelho2003 can create a general function at `helpers.ex` and truncate for this case only.

In the future, other people should reuse that function and truncate their text aswell.

2024-09-13 23:39 UTC, JoaoCoelho2003 commented
@joaodiaslobo 

> Keeping the whole text in the feed is definitely not the way to go but I also don't think we should limit what the organizations can write way too much (there still needs to exist a limit, but a bigger one). Maybe we should truncate the text on the post and allow the users to see the full content in the show page by clicking on the it.

In my opinion, we should truncate the text in the feed and, as Mario said, for the user to see the full post he would have to press it and check the announcement. About the text size limit, probably put a limit of around 500 characters or something like that.

![image](https://github.com/user-attachments/assets/25436979-e825-4cca-9141-27eb1eb002a4)

The text size limit varies a lot depending on the platform, but since this is an announcement, and announcements typically don’t require much text as they are meant to be brief, we could consider setting the limit lower.

2024-09-13 23:43 UTC, MarioRodrigues10 commented
I think 500 characters could be too much, check Instagram UI/UX for posts in either desktop or mobile i really like what they did, they truncate based on the text size.

2024-09-14 08:03 UTC, ruilopesm commented
We already have a function for truncating text, if I'm not mistaken. `maybe_slice_string/2` (we could change its name to `truncate` now that I think of it) 🙏

2024-11-07 16:56 UTC, FilipeR13 requested changes

2024-11-07 16:56 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/components/announcement_card.ex
> +  def announcement_card(assigns) do
![image](https://github.com/user-attachments/assets/56fdfaac-85d6-4856-9c2f-fd32cba412f8)
Should be a bottom border in the last announcement

2024-11-07 16:56 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/components/announcement_card.ex
> +          <p class="text-lg font-semibold text-zinc-900" title={@announcement.title}>
The activitys component is using `text-gray` instead of `text-zinc`. This is a issue in all code base, we should normalize this in another PR

2024-11-07 16:56 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/components/announcement_card.ex
> +            <img class="h-full w-full rounded-xl object-cover" src={Uploaders.Post.url({@announcement.image, @announcement}, :original)} alt="Announcement Image" />
![image](https://github.com/user-attachments/assets/a8ce88da-f4ad-4b57-a717-6cc0cd1fd68d)
I think in the mobile version the image doenst look really good with this level of rounded

2024-11-07 16:56 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/index.html.heex
> +  <.tabs></.tabs>
This solution to add the border in the page its not that good 😅, but I dont really know other solution. @joaodiaslobo any idea?

2024-11-07 17:34 UTC, joaodiaslobo commented on lib/atomic_web/live/announcement_live/index.html.heex
> +  <.tabs></.tabs>
The `page` component actually has a parameter to do this, called `bottom_border`. Unfortunately, it appears this functionality stopped working on a previous PR 😅.
@JoaoCoelho2003  Feel free to fix it and use it on this PR by making the following change in the `page` component:
```heex
def page(assigns) do
    ~H"""
    <div class="flex min-h-full flex-col items-stretch justify-between lg:flex-row">
      <div class="min-h-[100vh] flex w-full flex-col bg-white lg:flex-row lg:border-r">
        <main class="relative z-0 mb-10 flex-1 overflow-y-auto focus:outline-none xl:order-last">
          <div class={["mx-auto max-w-5xl px-4 sm:px-6 lg:px-8", @bottom_border && "border-b"]}>
            <div class="my-6 flex min-w-0 flex-row items-center justify-between"}>
              <h1 class="flex-1 select-none truncate text-2xl font-bold text-gray-900">
                <%= @title %>
              </h1>
              <%= render_slot(@actions) %>
            </div>
          </div>

          <%= render_slot(@inner_block) %>
        </main>
      </div>
    </div>
    """
  end
```

And use it like this:
```
<.page title="Announcements" bottom_border>
...
```

By the way, this PR is looking real good! 🤩 
Good job! 💪

2024-12-23 18:34 UTC, FilipeR13 requested changes

2024-12-23 18:34 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +    <.link navigate={Routes.announcement_show_path(@socket, :show, @announcement)}>
You shouldn't have a link to its own announcement on the show page.

2024-12-23 18:34 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +      <.button navigate={Routes.announcement_edit_path(@socket, :edit, @announcement.organization, @announcement)} icon="hero-pencil-solid"><%= gettext("Edit Announcement") %></.button>
![imagem](https://github.com/user-attachments/assets/39608bf5-cc7a-484b-b94c-32c7e9c81dfe)
As you can see, I can edit the announcement even though I am in a different organization.

2024-12-23 18:34 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +      <.button navigate={Routes.announcement_edit_path(@socket, :edit, @announcement.organization, @announcement)} icon="hero-pencil-solid"><%= gettext("Edit Announcement") %></.button>
![imagem](https://github.com/user-attachments/assets/082d63dc-23a4-4faf-8260-cbb731a87638)
The button should dissapear when seing as user and not as organization. If I click, this error is raised, is probably because of that
![imagem](https://github.com/user-attachments/assets/8b0dce6f-efd8-44be-88d1-77447f4b1099)

2024-12-23 18:34 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +      <.button navigate={Routes.announcement_edit_path(@socket, :edit, @announcement.organization, @announcement)} icon="hero-pencil-solid"><%= gettext("Edit Announcement") %></.button>
Replace the call to Routes.announcement_edit_path with the appropriate `~p` string.

2024-12-23 18:34 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +            <img class="h-full w-full object-cover md:rounded-xl" src={Uploaders.Post.url({@announcement.image, @announcement}, :original)} alt="Announcement Image" />
You need to limit the height of the image or this might happen:
![imagem](https://github.com/user-attachments/assets/8c62f9eb-b623-49c7-952e-d4f39a799429)
Try following the same strategy used on the main page

2025-01-07 16:23 UTC, FilipeR13 requested changes

2025-01-07 16:23 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +      <.button navigate={~p"/organizations/#{@announcement.organization}/announcements/#{@announcement}/edit"} icon="hero-pencil-solid"><%= gettext("Edit Announcement") %></.button>
There are two previous issues that still need to be fixed:
The button should disappear when viewing as a user or another organization.

View as a user and not organization:
![imagem](https://github.com/user-attachments/assets/23efe2aa-fb0f-4a20-aa61-169d88bb1a4b)

View as other organization:
![imagem](https://github.com/user-attachments/assets/b81d4b47-b2f1-4fbe-b3da-e40cd074cb72)

2025-01-07 16:32 UTC, JoaoCoelho2003 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +      <.button navigate={~p"/organizations/#{@announcement.organization}/announcements/#{@announcement}/edit"} icon="hero-pencil-solid"><%= gettext("Edit Announcement") %></.button>
This should be fixed, unless you are using a master account

2025-01-07 16:44 UTC, JoaoCoelho2003 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +      <.button navigate={~p"/organizations/#{@announcement.organization}/announcements/#{@announcement}/edit"} icon="hero-pencil-solid"><%= gettext("Edit Announcement") %></.button>
![image](https://github.com/user-attachments/assets/f0d02c0b-b6f3-47cb-804c-b047a7cad531)

Exactly, supposedly it is already working (let's not comment about the image used as an example)

2025-01-07 17:14 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +      <.button navigate={~p"/organizations/#{@announcement.organization}/announcements/#{@announcement}/edit"} icon="hero-pencil-solid"><%= gettext("Edit Announcement") %></.button>
You are correct in that sense.

However, when viewing as a master in user mode, the button appears—which may be fine—but attempting to edit raises this error:
![imagem](https://github.com/user-attachments/assets/6f994245-89ea-4b46-bfe5-b00ae7c2e143)

The first strategy to address this should be fixing the error. If that's not possible, consider hiding the button.

2025-02-04 14:04 UTC, FilipeR13 requested changes

2025-02-04 14:04 UTC, FilipeR13 commented on lib/atomic_web/live/announcement_live/show.html.heex
> +          <.avatar name={@announcement.organization.name} color={:light_zinc} size={:md} type={:organization} src={Uploaders.Logo.url({@announcement.organization.logo, @announcement.organization}, :o
There should be a link to the organization

2025-02-04 14:16 UTC, FilipeR13 approved these changes

2025-02-04 18:56 UTC, merged