feat: Improve image upload component
cesium/atomic pull request #536
Opened 2024-10-01 15:45 UTC by AfonsoMartins26

ibe the steps that you did to reproduce this._

2024-10-03 16:53 UTC, FilipeR13 submitted a review, later dismissed

2024-10-03 17:22 UTC, joaodiaslobo submitted a review, later dismissed
Can you also make it so that the component can be used multiple times in a single liveview? 👀

2024-10-03 17:22 UTC, joaodiaslobo commented on lib/atomic_web/components/image_uploader.ex
> +              <p class="text-xs text-gray-500">PNG, JPG, GIF up to 10MB</p>
This should be configurable 💡

2025-02-20 15:46 UTC, MarioRodrigues10 requested changes

2025-02-20 15:46 UTC, MarioRodrigues10 commented on lib/atomic/uploader.ex
> +        Keyword.get(unquote(opts), :max_size, 500)
Increase max size
```suggestion
        Keyword.get(unquote(opts), :max_size, 500)
```

2025-02-20 15:46 UTC, MarioRodrigues10 commented on lib/atomic_web/live/profile_live/form_component.ex
Upload not working

2025-02-21 10:38 UTC, MarioRodrigues10 requested changes
I uploaded an image of 22kb and then a 220kb image as a profile picture, and it doesn't showed any error in the UI but phoenix returned the following error. 

```
** (CaseClauseError) no case clause matching: {:error, #Ecto.Changeset<action: :update, changes: %{}, errors: [profile_picture: {"file size exceeds maximum allowed size", [type: Atomic.Uploaders.ProfilePicture.Type, validation: :cast]}], data: #Atomic.Accounts.User<>, valid?: false, ...>}
```

2025-02-27 11:25 UTC, MarioRodrigues10 requested changes

2025-02-27 11:25 UTC, MarioRodrigues10 commented on lib/atomic_web/live/profile_live/show.html.heex
> +      <!-- <% IO.inspect(@user) %> -->
```suggestion
```

2025-02-27 11:36 UTC, MarioRodrigues10 requested changes

2025-02-27 11:36 UTC, MarioRodrigues10 commented on lib/atomic_web/live/profile_live/form_component.ex
>    end
```suggestion
def handle_event("cancel-image", %{"ref" => ref}, socket) do
  uploads = [:profile_picture, :image_2]

  socket =
    Enum.reduce(uploads, socket, fn key, acc ->
      if Enum.any?(Map.get(acc.assigns.uploads, key, %{entries: []}).entries, &(&1.ref == ref)) do
        cancel_upload(acc, key, ref)
      else
        acc
      end
    end)

  {:noreply, socket}
end

```

2025-02-28 14:06 UTC, MarioRodrigues10 requested changes

2025-02-28 14:06 UTC, MarioRodrigues10 commented on lib/atomic_web/components/image_uploader.ex
>              <% end %>
Improve the way this is displayed

2025-02-28 14:06 UTC, MarioRodrigues10 commented on lib/atomic_web/components/image_uploader.ex
> +              </p>
Please move all this to a function and pass only the assign

2025-02-28 14:19 UTC, MarioRodrigues10 requested changes

2025-02-28 14:19 UTC, MarioRodrigues10 commented on lib/atomic_web/live/profile_live/form_component.html.heex
> +      <.live_component module={ImageUploader} icon="hero-cake" id="uploader-profile-picture_2" uploads={@uploads.image_2} target={@myself} class="h-100px w-100px" size_file={" #{@uploads.image_2.max_
```suggestion
      <.live_component module={ImageUploader} icon="hero-cake" id="uploader-profile-picture_1" uploads={@uploads.profile_picture} target={@myself} class="h-100px w-100px" size_file={" #{@uploads.profile_picture.max_file_size / 1_000_000} MB"} />
      <.live_component module={ImageUploader} icon="hero-cake" id="uploader-profile-picture_2" uploads={@uploads.image_2} target={@myself} class="h-100px w-100px" size_file={" #{@uploads.image_2.max_file_size / 1_000_000} MB"} />
```

Pass this conversion to the component at mount

2025-02-28 14:19 UTC, MarioRodrigues10 commented on lib/atomic_web/live/profile_live/form_component.html.heex
> +      <.live_component module={ImageUploader} icon="hero-cake" id="uploader-profile-picture_2" uploads={@uploads.image_2} target={@myself} class="h-100px w-100px" size_file={" #{@uploads.image_2.max_
Also make sure to change the icon, cake is not the most appropriate one

2025-03-03 21:21 UTC, MarioRodrigues10 requested changes

2025-03-03 21:21 UTC, MarioRodrigues10 commented on lib/atomic_web/components/image_uploader.ex
> +  def extencions_string(extensions) do
``` 
  def extensions_to_string(extensions) do
```

2025-03-03 21:26 UTC, MarioRodrigues10 approved these changes, later dismissed
:checkered_flag: :rocket:

2025-03-03 21:32 UTC, MarioRodrigues10 approved these changes
🏁 🚀

2025-03-04 19:56 UTC, merged

2025-03-05 10:24 UTC, joaodiaslobo commented
Unfortunately, this PR **needed more time in the oven**.
It broke the announcements form. 
Every time you change a component, make sure that all pages that use it **still work**.