feat: socials component
cesium/atomic pull request #538
Opened 2024-10-04 00:12 UTC by AfonsoMartins26

2024-10-07 10:52 UTC, MarioRodrigues10 requested changes

2024-10-07 10:52 UTC, MarioRodrigues10 commented on lib/atomic/uploaders/profile_picture.ex
> +  use Atomic.Uploader, extensions: ~w(.jpg .jpeg .png .gif), max_size: 500
```suggestion
  use Atomic.Uploader, extensions: ~w(.jpg .jpeg .png .gif)
```

2024-10-07 10:52 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +          ] do %>
Socials list should be configured inside the socials component, please define an outside function or variable which returns the socials.

```suggestion
      <div class="mt-4 flex gap-4">
        <%= for {social, icon, url_base} <- [
            {:tiktok, "tiktok.svg", "https://tiktok.com/"},
            {:instagram, "instagram.svg", "https://instagram.com/"},
            {:facebook, "facebook.svg", "https://facebook.com/"},
            {:x, "x.svg", "https://x.com/"}
          ] do %>
```

2024-10-07 10:52 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +                <%= social |> Atom.to_string() |> String.capitalize() %>
```suggestion
                <%= some_function(social)  %>
```
Please use a function from helpers module for this

2024-10-07 10:52 UTC, MarioRodrigues10 commented on lib/atomic_web/live/partner_live/show.html.heex
> +            <!-- Redes Sociais e Website -->
Keep it in english
```suggestion
            <!-- Redes Sociais e Website -->
```

2024-10-07 10:52 UTC, MarioRodrigues10 commented on lib/atomic_web/live/partner_live/show.html.heex
> +            <!-- Localização -->
Keep it in english
```suggestion
            <!-- Localização -->
```

2024-10-07 10:52 UTC, MarioRodrigues10 commented on lib/atomic_web/live/partner_live/show.html.heex
> +              <!-- Redes Sociais -->
Keep it in english
```suggestion
              <!-- Redes Sociais -->
```

2024-10-08 21:38 UTC, joaodiaslobo submitted a review, later dismissed

2024-10-08 21:38 UTC, joaodiaslobo commented on lib/atomic_web/components/socials.ex
> +          <% social_value = Map.get(@entity.socials, social) %>
This is a known pitfall when using heex templates. Learn more about it [here](https://hexdocs.pm/phoenix_live_view/assigns-eex.html#pitfalls).

2024-10-08 21:38 UTC, joaodiaslobo commented on lib/atomic_web/components/socials.ex
> +          ] do %>
```suggestion
  attr :socials, :map, required: true
  
  def socials(assigns) do
    ~H"""
      <div class="mt-4 flex gap-4">
        <%= for {social, icon, url_base} <- [
            {:tiktok, "tiktok.svg", "https://tiktok.com/"},
            {:instagram, "instagram.svg", "https://instagram.com/"},
            {:facebook, "facebook.svg", "https://facebook.com/"},
            {:x, "x.svg", "https://x.com/"}
          ] do %>
```

2024-10-08 21:38 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/show.html.heex
> +              <.socials entity={@partner} />
```suggestion
  <%= if @partner.socials do %>
              <.socials entity={@partner.socials} />
  <% end %>
```

2024-10-08 21:38 UTC, joaodiaslobo commented on lib/atomic_web/live/partner_live/show.ex
> +  import AtomicWeb.Components.Socials
```suggestion
  import AtomicWeb.Components.{Avatar, Socials}
```

2024-10-11 14:21 UTC, MarioRodrigues10 requested changes

2024-10-11 14:21 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +        <% social_value = Map.get(@entity, social) %>
This can't be defined here
```suggestion
```

2024-11-23 18:02 UTC, MarioRodrigues10 requested changes

2024-11-23 18:02 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +    <div class="mt-4 flex gap-4">
```suggestion
    <div class="flex gap-4">
```

2024-11-24 20:23 UTC, MarioRodrigues10 requested changes

2024-11-24 20:23 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +  alias AtomicWeb.Components.Helpers
```suggestion
  use Atomic.Web, :component
```

2024-11-24 20:23 UTC, MarioRodrigues10 commented on lib/atomic_web/components/helpers.ex
> +  end
This belongs to `helpers.ex` module not `helpers.ex` component

2024-11-25 22:20 UTC, FilipeR13 reviewed
After Mario suggestions, it may be ready to merge

2024-11-26 11:03 UTC, MarioRodrigues10 requested changes

2024-11-26 11:03 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +  use Atomic.Web, :component
```suggestion
  use AtomicWeb, :component
```

2024-11-26 11:03 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +  alias AtomicWeb.Helpers
```suggestion
```

2024-11-26 11:03 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +              <%= Helpers.atom_to_string_capitalize(social) %>
```suggestion
            <img src={"/images/" <> icon} class="h-5 w-5" alt={atom_to_string_capitalize(social)} />
            <.link class="text-blue-500" target="_blank" href={url_base <> social_value}>
              <% atom_to_string_capitalize(social) %>
```

2024-11-26 15:43 UTC, MarioRodrigues10 requested changes

2024-11-26 15:43 UTC, MarioRodrigues10 commented on lib/atomic_web/views/helpers.ex
> +  end
```suggestion
```

2024-11-26 15:43 UTC, MarioRodrigues10 commented on lib/atomic_web/components/socials.ex
> +              <%= atom_to_string_capitalize(social) %>
```suggestion
            <img src={"/images/" <> icon} class="h-5 w-5 capitalize" alt={Atom.to_string(social)} />
            <.link class="text-blue-500 capitalize" target="_blank" href={url_base <> social_value}>
              <%= Atom.to_string(social) %>
```

2024-11-27 14:15 UTC, MarioRodrigues10 approved these changes
:rocket:

2024-11-27 14:34 UTC, merged