Styling of all E-mails #544
cesium/atomic pull request #547
Opened 2024-12-04 09:29 UTC by LeandroCarvalho200409

## Description
_Provide a detailed description of the purpose of the changes included in this pull request. Optionally, include background information, relevant screenshots, and any other context that helps explain the work._

The purpose of this PR is to change the style of all the E-mail templates, so that they look legit and have a user-friendly design.

## Related Issues
_If applicable, specify the main parts of the application that will be impacted by this pull request._

#544 

## Steps to reproduce or test
_Describe the steps that you did to reproduce this._

2024-12-04 09:35 UTC, LeandroCarvalho200409 commented
Here's a first prototype of the E-mail styling for the E-mail confirmation mail.

![image](https://github.com/user-attachments/assets/49a3ccc9-e47d-4fda-9715-66ae93a002c3)

2024-12-06 12:29 UTC, joaodiaslobo requested changes
I like how it is looking! 🤩
Keep up the good work! 💪

2024-12-06 12:29 UTC, joaodiaslobo commented on lib/atomic_web/templates/email/user_confirmation.html.eex
> +            <p class="text-orange-700 mr-1">Hi</p>
```suggestion
            <p class="text-orange-700 mr-1">Hello</p>
```

2024-12-06 12:29 UTC, joaodiaslobo commented on lib/atomic_web/templates/email/user_confirmation.html.eex
> +            <p class="text-black"><%= @user.email %>!</p>
Pretty sure this exists, but not sure!
```suggestion
            <p class="text-black"><%= @user.name %>!</p>
```

2024-12-06 12:29 UTC, joaodiaslobo commented on lib/atomic_web/templates/email/user_confirmation.html.eex
> +        <p class="text-center mx-8">Welcome to the Atomic-Platform! You can confirm your Atomic account by clicking on the button bellow:</p>
```suggestion
        <p class="text-center mx-8">Welcome to Atomic! You can confirm your account by clicking on the button below:</p>
```

2024-12-06 12:29 UTC, joaodiaslobo commented on lib/atomic_web/templates/email/user_confirmation.html.eex
> +            <a class="bg-transparent text-orange-700 hover:text-white font-semibold border border-orange-500 hover:bg-orange-500 hover:border-transparent rounded py-2 px-4" href="<%= @url %>">Verify
```suggestion
            <a class="bg-transparent text-orange-700 hover:text-white font-semibold border border-orange-500 hover:bg-orange-500 hover:border-transparent rounded py-2 px-4" href={@url}>">Verify your account</a>
```

2025-02-27 18:35 UTC, enricoprazeres commented
Activity certificate: 
![image](https://github.com/user-attachments/assets/1a215c6e-c9b1-45f1-9ed3-24d7ceb20181)
This one cannot be tested on atomic because we don't have how to trigger this event yet, so I have just opened in another file.

Confirm account:
![image](https://github.com/user-attachments/assets/a34a5ba7-9689-49ec-bf94-578fa38aa816)

Reset password: 
![image](https://github.com/user-attachments/assets/70d92f63-355f-4e53-a018-f3da8697fe0d)

Collaborator accepted:
![image](https://github.com/user-attachments/assets/56ba4644-92a6-4b24-b33a-77b0fd5fd3de)

Collaborator request:
![image](https://github.com/user-attachments/assets/0e6e45d9-954a-4669-a426-454283a310ba)

2025-03-02 11:51 UTC, joaodiaslobo requested changes
Did you merge this accidentally with `main`? There are a lot of files (mainly images) being added from the old project

2025-03-02 11:56 UTC, joaodiaslobo requested changes
Style-wise this is looking really good!! 🤩

2025-03-02 11:56 UTC, joaodiaslobo commented on lib/atomic_web/templates/email/collaborator_request.html.eex
> +                    </p>
This information is duplicated, can you leave just one line?

2025-03-04 19:11 UTC, closed without merging